[project]
name = "anyforce"
version = "0.14.1"
description = ""
dependencies = [ "fastapi~=0.70", "uvicorn[standard]~=0.16", "pydantic[email]~=1.8", "python-jose[cryptography]~=3.3", "tortoise-orm==0.17.8", "passlib[bcrypt]~=1.7", "requests~=2.26", "types-requests~=2.26", "orjson~=3.6", "python-json-logger~=2.0", "Jinja2~=3.0", "colorama~=0.4", "aiohttp~=3.8", "starlette-context~=0.3", "itsdangerous~=2.0", "inflection~=0.5", "aenum~=3.1", "python-dateutil~=2.8", "rq~=1.10",]
requires-python = ">=3.8"
[[project.authors]]
name = "exherb"
email = "i@4leaf.me"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "COPYRIGHT"

[project.urls]
homepage = "https://github.com/42signal/anyforce"

[project.optional-dependencies]

[tool.pdm]
includes = [ "anyforce/**/*.py", "anyforce/py.typed", "README.md",]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
verify_ssl = true

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3

[tool.pdm.dev-dependencies]
dev = [ "flake8~=4.0", "isort~=5.10", "black~=21.12b0", "pytest~=6.2", "typer~=0.4", "pytest-asyncio~=0.16", "Faker~=10.0", "pytest-cov~=3.0", "twine~=3.7",]

[tool.pytest.ini_options]
testpaths = [ "tests",]
