[tool.poetry]
name = "roche_aws"
version = "0.0.0"
description = "Empty roche_aws for security reasons"
authors = ["Iwan Silvan Bolzern <iwan.bolzern@roche.com>"]
packages = [
    { include = "roche_aws" },
]


[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
