[tool.poetry]
name = "LavaAPI"
version = "1.0.0"
description = "A simple library for accepting payments and using the LAVA Wallet"
authors = ["billiedark"]
license = "GNU General Public License (GPL)"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
