[tool.poetry]
name = "nonebot_plugin_what2eat"
version = "0.1.0"
description = "What to eat today for your breakfast, lunch, dinner and even midnight snack!"
authors = ["KafCoppelia <k740677208@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
