[tool.poetry]
name = "formsg-python-sdk"
version = "0.1.0"
description = ""
authors = ["Chin Ying <chinying@open.gov.sg>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.2"
PyNaCl = "^1.5.0"
pytest = "^6.2.5"

[tool.poetry.dev-dependencies]
Flask = "^2.0.2"
black = "^21.12b0"
mypy = "^0.931"
twine = "^3.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
