# coding: utf-8

"""
    BAPP API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.models.inline_response20068_extra import InlineResponse20068Extra  # noqa: E501
from bapp_api_client.rest import ApiException


class TestInlineResponse20068Extra(unittest.TestCase):
    """InlineResponse20068Extra unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20068Extra(self):
        """Test InlineResponse20068Extra"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bapp_api_client.models.inline_response20068_extra.InlineResponse20068Extra()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
