[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.check-manifest]
ignore = [
    "Pipfile", "Pipfile.lock",
    "make_win_package.bat", "deploy.bat",
    "setup_cx.py", "setup_iss.py", "setup_template.iss",
    "doc/**",
    "demos/**",
    "tools/**",
    "contrib/**",
    "tests/**",
    "unittests/**" ]
