# coding: utf-8

"""
    BAPP API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bapp_api_client.configuration import Configuration


class DocumentsReportPdf(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'document_date_month': 'int',
        'document_date_year': 'int'
    }

    attribute_map = {
        'document_date_month': 'document_date_month',
        'document_date_year': 'document_date_year'
    }

    def __init__(self, document_date_month=None, document_date_year=None, _configuration=None):  # noqa: E501
        """DocumentsReportPdf - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._document_date_month = None
        self._document_date_year = None
        self.discriminator = None

        self.document_date_month = document_date_month
        self.document_date_year = document_date_year

    @property
    def document_date_month(self):
        """Gets the document_date_month of this DocumentsReportPdf.  # noqa: E501


        :return: The document_date_month of this DocumentsReportPdf.  # noqa: E501
        :rtype: int
        """
        return self._document_date_month

    @document_date_month.setter
    def document_date_month(self, document_date_month):
        """Sets the document_date_month of this DocumentsReportPdf.


        :param document_date_month: The document_date_month of this DocumentsReportPdf.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and document_date_month is None:
            raise ValueError("Invalid value for `document_date_month`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                document_date_month is not None and document_date_month > 12):  # noqa: E501
            raise ValueError("Invalid value for `document_date_month`, must be a value less than or equal to `12`")  # noqa: E501
        if (self._configuration.client_side_validation and
                document_date_month is not None and document_date_month < 1):  # noqa: E501
            raise ValueError("Invalid value for `document_date_month`, must be a value greater than or equal to `1`")  # noqa: E501

        self._document_date_month = document_date_month

    @property
    def document_date_year(self):
        """Gets the document_date_year of this DocumentsReportPdf.  # noqa: E501


        :return: The document_date_year of this DocumentsReportPdf.  # noqa: E501
        :rtype: int
        """
        return self._document_date_year

    @document_date_year.setter
    def document_date_year(self, document_date_year):
        """Sets the document_date_year of this DocumentsReportPdf.


        :param document_date_year: The document_date_year of this DocumentsReportPdf.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and document_date_year is None:
            raise ValueError("Invalid value for `document_date_year`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                document_date_year is not None and document_date_year < 1990):  # noqa: E501
            raise ValueError("Invalid value for `document_date_year`, must be a value greater than or equal to `1990`")  # noqa: E501

        self._document_date_year = document_date_year

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocumentsReportPdf, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentsReportPdf):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DocumentsReportPdf):
            return True

        return self.to_dict() != other.to_dict()
