"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class _StreamRequestType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StreamRequestTypeEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[
        _StreamRequestType.ValueType
    ],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    StreamRequestTypeUnknown: StreamRequestType.ValueType = ...  # 0
    ReceiveMessage: StreamRequestType.ValueType = ...  # 1
    AckMessage: StreamRequestType.ValueType = ...  # 2
    RejectMessage: StreamRequestType.ValueType = ...  # 3
    ModifyVisibility: StreamRequestType.ValueType = ...  # 4
    ResendMessage: StreamRequestType.ValueType = ...  # 5
    SendModifiedMessage: StreamRequestType.ValueType = ...  # 6

class StreamRequestType(
    _StreamRequestType, metaclass=_StreamRequestTypeEnumTypeWrapper
):
    pass

StreamRequestTypeUnknown: StreamRequestType.ValueType = ...  # 0
ReceiveMessage: StreamRequestType.ValueType = ...  # 1
AckMessage: StreamRequestType.ValueType = ...  # 2
RejectMessage: StreamRequestType.ValueType = ...  # 3
ModifyVisibility: StreamRequestType.ValueType = ...  # 4
ResendMessage: StreamRequestType.ValueType = ...  # 5
SendModifiedMessage: StreamRequestType.ValueType = ...  # 6
global___StreamRequestType = StreamRequestType

class PingResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    HOST_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    SERVERSTARTTIME_FIELD_NUMBER: builtins.int
    SERVERUPTIMESECONDS_FIELD_NUMBER: builtins.int
    Host: typing.Text = ...
    Version: typing.Text = ...
    ServerStartTime: builtins.int = ...
    ServerUpTimeSeconds: builtins.int = ...
    def __init__(
        self,
        *,
        Host: typing.Text = ...,
        Version: typing.Text = ...,
        ServerStartTime: builtins.int = ...,
        ServerUpTimeSeconds: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "Host",
            b"Host",
            "ServerStartTime",
            b"ServerStartTime",
            "ServerUpTimeSeconds",
            b"ServerUpTimeSeconds",
            "Version",
            b"Version",
        ],
    ) -> None: ...

global___PingResult = PingResult

class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(
        self,
    ) -> None: ...

global___Empty = Empty

class Result(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    EVENTID_FIELD_NUMBER: builtins.int
    SENT_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    EventID: typing.Text = ...
    Sent: builtins.bool = ...
    Error: typing.Text = ...
    def __init__(
        self,
        *,
        EventID: typing.Text = ...,
        Sent: builtins.bool = ...,
        Error: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "Error", b"Error", "EventID", b"EventID", "Sent", b"Sent"
        ],
    ) -> None: ...

global___Result = Result

class Event(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(
            self,
            *,
            key: typing.Text = ...,
            value: typing.Text = ...,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions.Literal["key", b"key", "value", b"value"],
        ) -> None: ...
    EVENTID_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    STORE_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    EventID: typing.Text = ...
    ClientID: typing.Text = ...
    Channel: typing.Text = ...
    Metadata: typing.Text = ...
    Body: builtins.bytes = ...
    Store: builtins.bool = ...
    @property
    def Tags(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    def __init__(
        self,
        *,
        EventID: typing.Text = ...,
        ClientID: typing.Text = ...,
        Channel: typing.Text = ...,
        Metadata: typing.Text = ...,
        Body: builtins.bytes = ...,
        Store: builtins.bool = ...,
        Tags: typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "Body",
            b"Body",
            "Channel",
            b"Channel",
            "ClientID",
            b"ClientID",
            "EventID",
            b"EventID",
            "Metadata",
            b"Metadata",
            "Store",
            b"Store",
            "Tags",
            b"Tags",
        ],
    ) -> None: ...

global___Event = Event

class EventReceive(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(
            self,
            *,
            key: typing.Text = ...,
            value: typing.Text = ...,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions.Literal["key", b"key", "value", b"value"],
        ) -> None: ...
    EVENTID_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    SEQUENCE_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    EventID: typing.Text = ...
    Channel: typing.Text = ...
    Metadata: typing.Text = ...
    Body: builtins.bytes = ...
    Timestamp: builtins.int = ...
    Sequence: builtins.int = ...
    @property
    def Tags(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    def __init__(
        self,
        *,
        EventID: typing.Text = ...,
        Channel: typing.Text = ...,
        Metadata: typing.Text = ...,
        Body: builtins.bytes = ...,
        Timestamp: builtins.int = ...,
        Sequence: builtins.int = ...,
        Tags: typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "Body",
            b"Body",
            "Channel",
            b"Channel",
            "EventID",
            b"EventID",
            "Metadata",
            b"Metadata",
            "Sequence",
            b"Sequence",
            "Tags",
            b"Tags",
            "Timestamp",
            b"Timestamp",
        ],
    ) -> None: ...

global___EventReceive = EventReceive

class Subscribe(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _SubscribeType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _SubscribeTypeEnumTypeWrapper(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[
            _SubscribeType.ValueType
        ],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        SubscribeTypeUndefined: Subscribe.SubscribeType.ValueType = ...  # 0
        Events: Subscribe.SubscribeType.ValueType = ...  # 1
        EventsStore: Subscribe.SubscribeType.ValueType = ...  # 2
        Commands: Subscribe.SubscribeType.ValueType = ...  # 3
        Queries: Subscribe.SubscribeType.ValueType = ...  # 4
    class SubscribeType(_SubscribeType, metaclass=_SubscribeTypeEnumTypeWrapper):
        pass
    SubscribeTypeUndefined: Subscribe.SubscribeType.ValueType = ...  # 0
    Events: Subscribe.SubscribeType.ValueType = ...  # 1
    EventsStore: Subscribe.SubscribeType.ValueType = ...  # 2
    Commands: Subscribe.SubscribeType.ValueType = ...  # 3
    Queries: Subscribe.SubscribeType.ValueType = ...  # 4
    class _EventsStoreType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _EventsStoreTypeEnumTypeWrapper(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[
            _EventsStoreType.ValueType
        ],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        EventsStoreTypeUndefined: Subscribe.EventsStoreType.ValueType = ...  # 0
        StartNewOnly: Subscribe.EventsStoreType.ValueType = ...  # 1
        StartFromFirst: Subscribe.EventsStoreType.ValueType = ...  # 2
        StartFromLast: Subscribe.EventsStoreType.ValueType = ...  # 3
        StartAtSequence: Subscribe.EventsStoreType.ValueType = ...  # 4
        StartAtTime: Subscribe.EventsStoreType.ValueType = ...  # 5
        StartAtTimeDelta: Subscribe.EventsStoreType.ValueType = ...  # 6
    class EventsStoreType(_EventsStoreType, metaclass=_EventsStoreTypeEnumTypeWrapper):
        pass
    EventsStoreTypeUndefined: Subscribe.EventsStoreType.ValueType = ...  # 0
    StartNewOnly: Subscribe.EventsStoreType.ValueType = ...  # 1
    StartFromFirst: Subscribe.EventsStoreType.ValueType = ...  # 2
    StartFromLast: Subscribe.EventsStoreType.ValueType = ...  # 3
    StartAtSequence: Subscribe.EventsStoreType.ValueType = ...  # 4
    StartAtTime: Subscribe.EventsStoreType.ValueType = ...  # 5
    StartAtTimeDelta: Subscribe.EventsStoreType.ValueType = ...  # 6

    SUBSCRIBETYPEDATA_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    GROUP_FIELD_NUMBER: builtins.int
    EVENTSSTORETYPEDATA_FIELD_NUMBER: builtins.int
    EVENTSSTORETYPEVALUE_FIELD_NUMBER: builtins.int
    SubscribeTypeData: global___Subscribe.SubscribeType.ValueType = ...
    ClientID: typing.Text = ...
    Channel: typing.Text = ...
    Group: typing.Text = ...
    EventsStoreTypeData: global___Subscribe.EventsStoreType.ValueType = ...
    EventsStoreTypeValue: builtins.int = ...
    def __init__(
        self,
        *,
        SubscribeTypeData: global___Subscribe.SubscribeType.ValueType = ...,
        ClientID: typing.Text = ...,
        Channel: typing.Text = ...,
        Group: typing.Text = ...,
        EventsStoreTypeData: global___Subscribe.EventsStoreType.ValueType = ...,
        EventsStoreTypeValue: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "Channel",
            b"Channel",
            "ClientID",
            b"ClientID",
            "EventsStoreTypeData",
            b"EventsStoreTypeData",
            "EventsStoreTypeValue",
            b"EventsStoreTypeValue",
            "Group",
            b"Group",
            "SubscribeTypeData",
            b"SubscribeTypeData",
        ],
    ) -> None: ...

global___Subscribe = Subscribe

class Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _RequestType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _RequestTypeEnumTypeWrapper(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[
            _RequestType.ValueType
        ],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        RequestTypeUnknown: Request.RequestType.ValueType = ...  # 0
        Command: Request.RequestType.ValueType = ...  # 1
        Query: Request.RequestType.ValueType = ...  # 2
    class RequestType(_RequestType, metaclass=_RequestTypeEnumTypeWrapper):
        pass
    RequestTypeUnknown: Request.RequestType.ValueType = ...  # 0
    Command: Request.RequestType.ValueType = ...  # 1
    Query: Request.RequestType.ValueType = ...  # 2
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(
            self,
            *,
            key: typing.Text = ...,
            value: typing.Text = ...,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions.Literal["key", b"key", "value", b"value"],
        ) -> None: ...
    REQUESTID_FIELD_NUMBER: builtins.int
    REQUESTTYPEDATA_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    REPLYCHANNEL_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    CACHEKEY_FIELD_NUMBER: builtins.int
    CACHETTL_FIELD_NUMBER: builtins.int
    SPAN_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    RequestID: typing.Text = ...
    RequestTypeData: global___Request.RequestType.ValueType = ...
    ClientID: typing.Text = ...
    Channel: typing.Text = ...
    Metadata: typing.Text = ...
    Body: builtins.bytes = ...
    ReplyChannel: typing.Text = ...
    Timeout: builtins.int = ...
    CacheKey: typing.Text = ...
    CacheTTL: builtins.int = ...
    Span: builtins.bytes = ...
    @property
    def Tags(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    def __init__(
        self,
        *,
        RequestID: typing.Text = ...,
        RequestTypeData: global___Request.RequestType.ValueType = ...,
        ClientID: typing.Text = ...,
        Channel: typing.Text = ...,
        Metadata: typing.Text = ...,
        Body: builtins.bytes = ...,
        ReplyChannel: typing.Text = ...,
        Timeout: builtins.int = ...,
        CacheKey: typing.Text = ...,
        CacheTTL: builtins.int = ...,
        Span: builtins.bytes = ...,
        Tags: typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "Body",
            b"Body",
            "CacheKey",
            b"CacheKey",
            "CacheTTL",
            b"CacheTTL",
            "Channel",
            b"Channel",
            "ClientID",
            b"ClientID",
            "Metadata",
            b"Metadata",
            "ReplyChannel",
            b"ReplyChannel",
            "RequestID",
            b"RequestID",
            "RequestTypeData",
            b"RequestTypeData",
            "Span",
            b"Span",
            "Tags",
            b"Tags",
            "Timeout",
            b"Timeout",
        ],
    ) -> None: ...

global___Request = Request

class Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(
            self,
            *,
            key: typing.Text = ...,
            value: typing.Text = ...,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions.Literal["key", b"key", "value", b"value"],
        ) -> None: ...
    CLIENTID_FIELD_NUMBER: builtins.int
    REQUESTID_FIELD_NUMBER: builtins.int
    REPLYCHANNEL_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    CACHEHIT_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    EXECUTED_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    SPAN_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    ClientID: typing.Text = ...
    RequestID: typing.Text = ...
    ReplyChannel: typing.Text = ...
    Metadata: typing.Text = ...
    Body: builtins.bytes = ...
    CacheHit: builtins.bool = ...
    Timestamp: builtins.int = ...
    Executed: builtins.bool = ...
    Error: typing.Text = ...
    Span: builtins.bytes = ...
    @property
    def Tags(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    def __init__(
        self,
        *,
        ClientID: typing.Text = ...,
        RequestID: typing.Text = ...,
        ReplyChannel: typing.Text = ...,
        Metadata: typing.Text = ...,
        Body: builtins.bytes = ...,
        CacheHit: builtins.bool = ...,
        Timestamp: builtins.int = ...,
        Executed: builtins.bool = ...,
        Error: typing.Text = ...,
        Span: builtins.bytes = ...,
        Tags: typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "Body",
            b"Body",
            "CacheHit",
            b"CacheHit",
            "ClientID",
            b"ClientID",
            "Error",
            b"Error",
            "Executed",
            b"Executed",
            "Metadata",
            b"Metadata",
            "ReplyChannel",
            b"ReplyChannel",
            "RequestID",
            b"RequestID",
            "Span",
            b"Span",
            "Tags",
            b"Tags",
            "Timestamp",
            b"Timestamp",
        ],
    ) -> None: ...

global___Response = Response

class QueueMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(
            self,
            *,
            key: typing.Text = ...,
            value: typing.Text = ...,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions.Literal["key", b"key", "value", b"value"],
        ) -> None: ...
    MESSAGEID_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    POLICY_FIELD_NUMBER: builtins.int
    MessageID: typing.Text = ...
    ClientID: typing.Text = ...
    Channel: typing.Text = ...
    Metadata: typing.Text = ...
    Body: builtins.bytes = ...
    @property
    def Tags(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    @property
    def Attributes(self) -> global___QueueMessageAttributes: ...
    @property
    def Policy(self) -> global___QueueMessagePolicy: ...
    def __init__(
        self,
        *,
        MessageID: typing.Text = ...,
        ClientID: typing.Text = ...,
        Channel: typing.Text = ...,
        Metadata: typing.Text = ...,
        Body: builtins.bytes = ...,
        Tags: typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        Attributes: typing.Optional[global___QueueMessageAttributes] = ...,
        Policy: typing.Optional[global___QueueMessagePolicy] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "Attributes", b"Attributes", "Policy", b"Policy"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "Attributes",
            b"Attributes",
            "Body",
            b"Body",
            "Channel",
            b"Channel",
            "ClientID",
            b"ClientID",
            "MessageID",
            b"MessageID",
            "Metadata",
            b"Metadata",
            "Policy",
            b"Policy",
            "Tags",
            b"Tags",
        ],
    ) -> None: ...

global___QueueMessage = QueueMessage

class QueueMessagesBatchRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    BATCHID_FIELD_NUMBER: builtins.int
    MESSAGES_FIELD_NUMBER: builtins.int
    BatchID: typing.Text = ...
    @property
    def Messages(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___QueueMessage
    ]: ...
    def __init__(
        self,
        *,
        BatchID: typing.Text = ...,
        Messages: typing.Optional[typing.Iterable[global___QueueMessage]] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "BatchID", b"BatchID", "Messages", b"Messages"
        ],
    ) -> None: ...

global___QueueMessagesBatchRequest = QueueMessagesBatchRequest

class QueueMessagesBatchResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    BATCHID_FIELD_NUMBER: builtins.int
    RESULTS_FIELD_NUMBER: builtins.int
    HAVEERRORS_FIELD_NUMBER: builtins.int
    BatchID: typing.Text = ...
    @property
    def Results(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___SendQueueMessageResult
    ]: ...
    HaveErrors: builtins.bool = ...
    def __init__(
        self,
        *,
        BatchID: typing.Text = ...,
        Results: typing.Optional[
            typing.Iterable[global___SendQueueMessageResult]
        ] = ...,
        HaveErrors: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "BatchID", b"BatchID", "HaveErrors", b"HaveErrors", "Results", b"Results"
        ],
    ) -> None: ...

global___QueueMessagesBatchResponse = QueueMessagesBatchResponse

class QueueMessageAttributes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TIMESTAMP_FIELD_NUMBER: builtins.int
    SEQUENCE_FIELD_NUMBER: builtins.int
    MD5OFBODY_FIELD_NUMBER: builtins.int
    RECEIVECOUNT_FIELD_NUMBER: builtins.int
    REROUTED_FIELD_NUMBER: builtins.int
    REROUTEDFROMQUEUE_FIELD_NUMBER: builtins.int
    EXPIRATIONAT_FIELD_NUMBER: builtins.int
    DELAYEDTO_FIELD_NUMBER: builtins.int
    Timestamp: builtins.int = ...
    Sequence: builtins.int = ...
    MD5OfBody: typing.Text = ...
    ReceiveCount: builtins.int = ...
    ReRouted: builtins.bool = ...
    ReRoutedFromQueue: typing.Text = ...
    ExpirationAt: builtins.int = ...
    DelayedTo: builtins.int = ...
    def __init__(
        self,
        *,
        Timestamp: builtins.int = ...,
        Sequence: builtins.int = ...,
        MD5OfBody: typing.Text = ...,
        ReceiveCount: builtins.int = ...,
        ReRouted: builtins.bool = ...,
        ReRoutedFromQueue: typing.Text = ...,
        ExpirationAt: builtins.int = ...,
        DelayedTo: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "DelayedTo",
            b"DelayedTo",
            "ExpirationAt",
            b"ExpirationAt",
            "MD5OfBody",
            b"MD5OfBody",
            "ReRouted",
            b"ReRouted",
            "ReRoutedFromQueue",
            b"ReRoutedFromQueue",
            "ReceiveCount",
            b"ReceiveCount",
            "Sequence",
            b"Sequence",
            "Timestamp",
            b"Timestamp",
        ],
    ) -> None: ...

global___QueueMessageAttributes = QueueMessageAttributes

class QueueMessagePolicy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    EXPIRATIONSECONDS_FIELD_NUMBER: builtins.int
    DELAYSECONDS_FIELD_NUMBER: builtins.int
    MAXRECEIVECOUNT_FIELD_NUMBER: builtins.int
    MAXRECEIVEQUEUE_FIELD_NUMBER: builtins.int
    ExpirationSeconds: builtins.int = ...
    DelaySeconds: builtins.int = ...
    MaxReceiveCount: builtins.int = ...
    MaxReceiveQueue: typing.Text = ...
    def __init__(
        self,
        *,
        ExpirationSeconds: builtins.int = ...,
        DelaySeconds: builtins.int = ...,
        MaxReceiveCount: builtins.int = ...,
        MaxReceiveQueue: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "DelaySeconds",
            b"DelaySeconds",
            "ExpirationSeconds",
            b"ExpirationSeconds",
            "MaxReceiveCount",
            b"MaxReceiveCount",
            "MaxReceiveQueue",
            b"MaxReceiveQueue",
        ],
    ) -> None: ...

global___QueueMessagePolicy = QueueMessagePolicy

class SendQueueMessageResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MESSAGEID_FIELD_NUMBER: builtins.int
    SENTAT_FIELD_NUMBER: builtins.int
    EXPIRATIONAT_FIELD_NUMBER: builtins.int
    DELAYEDTO_FIELD_NUMBER: builtins.int
    ISERROR_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    MessageID: typing.Text = ...
    SentAt: builtins.int = ...
    ExpirationAt: builtins.int = ...
    DelayedTo: builtins.int = ...
    IsError: builtins.bool = ...
    Error: typing.Text = ...
    def __init__(
        self,
        *,
        MessageID: typing.Text = ...,
        SentAt: builtins.int = ...,
        ExpirationAt: builtins.int = ...,
        DelayedTo: builtins.int = ...,
        IsError: builtins.bool = ...,
        Error: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "DelayedTo",
            b"DelayedTo",
            "Error",
            b"Error",
            "ExpirationAt",
            b"ExpirationAt",
            "IsError",
            b"IsError",
            "MessageID",
            b"MessageID",
            "SentAt",
            b"SentAt",
        ],
    ) -> None: ...

global___SendQueueMessageResult = SendQueueMessageResult

class ReceiveQueueMessagesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    REQUESTID_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    MAXNUMBEROFMESSAGES_FIELD_NUMBER: builtins.int
    WAITTIMESECONDS_FIELD_NUMBER: builtins.int
    ISPEAK_FIELD_NUMBER: builtins.int
    RequestID: typing.Text = ...
    ClientID: typing.Text = ...
    Channel: typing.Text = ...
    MaxNumberOfMessages: builtins.int = ...
    WaitTimeSeconds: builtins.int = ...
    IsPeak: builtins.bool = ...
    def __init__(
        self,
        *,
        RequestID: typing.Text = ...,
        ClientID: typing.Text = ...,
        Channel: typing.Text = ...,
        MaxNumberOfMessages: builtins.int = ...,
        WaitTimeSeconds: builtins.int = ...,
        IsPeak: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "Channel",
            b"Channel",
            "ClientID",
            b"ClientID",
            "IsPeak",
            b"IsPeak",
            "MaxNumberOfMessages",
            b"MaxNumberOfMessages",
            "RequestID",
            b"RequestID",
            "WaitTimeSeconds",
            b"WaitTimeSeconds",
        ],
    ) -> None: ...

global___ReceiveQueueMessagesRequest = ReceiveQueueMessagesRequest

class ReceiveQueueMessagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    REQUESTID_FIELD_NUMBER: builtins.int
    MESSAGES_FIELD_NUMBER: builtins.int
    MESSAGESRECEIVED_FIELD_NUMBER: builtins.int
    MESSAGESEXPIRED_FIELD_NUMBER: builtins.int
    ISPEAK_FIELD_NUMBER: builtins.int
    ISERROR_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    RequestID: typing.Text = ...
    @property
    def Messages(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___QueueMessage
    ]: ...
    MessagesReceived: builtins.int = ...
    MessagesExpired: builtins.int = ...
    IsPeak: builtins.bool = ...
    IsError: builtins.bool = ...
    Error: typing.Text = ...
    def __init__(
        self,
        *,
        RequestID: typing.Text = ...,
        Messages: typing.Optional[typing.Iterable[global___QueueMessage]] = ...,
        MessagesReceived: builtins.int = ...,
        MessagesExpired: builtins.int = ...,
        IsPeak: builtins.bool = ...,
        IsError: builtins.bool = ...,
        Error: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "Error",
            b"Error",
            "IsError",
            b"IsError",
            "IsPeak",
            b"IsPeak",
            "Messages",
            b"Messages",
            "MessagesExpired",
            b"MessagesExpired",
            "MessagesReceived",
            b"MessagesReceived",
            "RequestID",
            b"RequestID",
        ],
    ) -> None: ...

global___ReceiveQueueMessagesResponse = ReceiveQueueMessagesResponse

class AckAllQueueMessagesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    REQUESTID_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    WAITTIMESECONDS_FIELD_NUMBER: builtins.int
    RequestID: typing.Text = ...
    ClientID: typing.Text = ...
    Channel: typing.Text = ...
    WaitTimeSeconds: builtins.int = ...
    def __init__(
        self,
        *,
        RequestID: typing.Text = ...,
        ClientID: typing.Text = ...,
        Channel: typing.Text = ...,
        WaitTimeSeconds: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "Channel",
            b"Channel",
            "ClientID",
            b"ClientID",
            "RequestID",
            b"RequestID",
            "WaitTimeSeconds",
            b"WaitTimeSeconds",
        ],
    ) -> None: ...

global___AckAllQueueMessagesRequest = AckAllQueueMessagesRequest

class AckAllQueueMessagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    REQUESTID_FIELD_NUMBER: builtins.int
    AFFECTEDMESSAGES_FIELD_NUMBER: builtins.int
    ISERROR_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    RequestID: typing.Text = ...
    AffectedMessages: builtins.int = ...
    IsError: builtins.bool = ...
    Error: typing.Text = ...
    def __init__(
        self,
        *,
        RequestID: typing.Text = ...,
        AffectedMessages: builtins.int = ...,
        IsError: builtins.bool = ...,
        Error: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "AffectedMessages",
            b"AffectedMessages",
            "Error",
            b"Error",
            "IsError",
            b"IsError",
            "RequestID",
            b"RequestID",
        ],
    ) -> None: ...

global___AckAllQueueMessagesResponse = AckAllQueueMessagesResponse

class StreamQueueMessagesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    REQUESTID_FIELD_NUMBER: builtins.int
    CLIENTID_FIELD_NUMBER: builtins.int
    STREAMREQUESTTYPEDATA_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    VISIBILITYSECONDS_FIELD_NUMBER: builtins.int
    WAITTIMESECONDS_FIELD_NUMBER: builtins.int
    REFSEQUENCE_FIELD_NUMBER: builtins.int
    MODIFIEDMESSAGE_FIELD_NUMBER: builtins.int
    RequestID: typing.Text = ...
    ClientID: typing.Text = ...
    StreamRequestTypeData: global___StreamRequestType.ValueType = ...
    Channel: typing.Text = ...
    VisibilitySeconds: builtins.int = ...
    WaitTimeSeconds: builtins.int = ...
    RefSequence: builtins.int = ...
    @property
    def ModifiedMessage(self) -> global___QueueMessage: ...
    def __init__(
        self,
        *,
        RequestID: typing.Text = ...,
        ClientID: typing.Text = ...,
        StreamRequestTypeData: global___StreamRequestType.ValueType = ...,
        Channel: typing.Text = ...,
        VisibilitySeconds: builtins.int = ...,
        WaitTimeSeconds: builtins.int = ...,
        RefSequence: builtins.int = ...,
        ModifiedMessage: typing.Optional[global___QueueMessage] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["ModifiedMessage", b"ModifiedMessage"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "Channel",
            b"Channel",
            "ClientID",
            b"ClientID",
            "ModifiedMessage",
            b"ModifiedMessage",
            "RefSequence",
            b"RefSequence",
            "RequestID",
            b"RequestID",
            "StreamRequestTypeData",
            b"StreamRequestTypeData",
            "VisibilitySeconds",
            b"VisibilitySeconds",
            "WaitTimeSeconds",
            b"WaitTimeSeconds",
        ],
    ) -> None: ...

global___StreamQueueMessagesRequest = StreamQueueMessagesRequest

class StreamQueueMessagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    REQUESTID_FIELD_NUMBER: builtins.int
    STREAMREQUESTTYPEDATA_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ISERROR_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    RequestID: typing.Text = ...
    StreamRequestTypeData: global___StreamRequestType.ValueType = ...
    @property
    def Message(self) -> global___QueueMessage: ...
    IsError: builtins.bool = ...
    Error: typing.Text = ...
    def __init__(
        self,
        *,
        RequestID: typing.Text = ...,
        StreamRequestTypeData: global___StreamRequestType.ValueType = ...,
        Message: typing.Optional[global___QueueMessage] = ...,
        IsError: builtins.bool = ...,
        Error: typing.Text = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["Message", b"Message"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "Error",
            b"Error",
            "IsError",
            b"IsError",
            "Message",
            b"Message",
            "RequestID",
            b"RequestID",
            "StreamRequestTypeData",
            b"StreamRequestTypeData",
        ],
    ) -> None: ...

global___StreamQueueMessagesResponse = StreamQueueMessagesResponse
