package_name: iris_hector_patino

training_data_file: train.csv
test_data_file: test.csv
id_column: Id
random_state: 42
test_size: 0.2
features_to_combine:
  - SepalLengthCm
  - SepalWidthCm
  - PetalLengthCm
  - PetalWidthCm
target: Species
shuffle: true

pipeline_name: pipeline_iris
pipeline_save_file: pipeline_model_output_v

n_estimators: 16
learning_rate: 5.869262439392996
max_depth: 4
gamma: 1.3381078668366866
subsample: 0.38674136078825716
