[tool.poetry]
name = "clammy"
version = "1.0.0"
description = ""
authors = ["ranguli <hello@joshmurphy.ca>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.12b0"
flake8 = "^4.0.1"
nox = "^2022.1.7"
nox-poetry = "^0.9.0"
bandit = "^1.7.1"
pylint = "^2.12.2"
isort = "^5.10.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
