
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-23T16:22:16-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7f9a76e4b160099d73192c3faac7095ec21c108",
 "version": "2.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
