
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-23T21:08:09-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3be7a995c61c38f4295cad6018bc8f0299d43a40",
 "version": "4.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
