[tool.poetry]
name = "PIModelManager"
version = "0.8.3"
description = "A package used to manage our ML models."
readme = "README.md"
authors = ["Martin Kirilov"]
license = "Pandora Intelligence"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
ray = {extras = ["serve"], version = "^1.7.1"}
aioify = "^0.4.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.0"
pytest = "^6.2.2"
black = {version = "^20.8b1", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
