
[tool.poetry]
name = "ztask"
version = "0.1.2"
description = "Ztask, the terminal interface to log task in zohoprojects and complete the damned timesheets with a Taskwarrior inspired syntax."
authors = ["Pablo Ruiz"]
license = "GPLv2"
readme = "readme.md"
homepage = "https://github.com/PabloRuizCuevas/ztask"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.5"
prettyprint = "^0.1.5"
parsedatetime = "^2.6"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
ztask = 'ztask:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

