[tool.poetry]
name = "ml_init"
version = "0.6.0"
description = "Install the main ML libraries"
authors = ["Alberto Rubiales <al.rubiales.b@gmail.com>"]
readme = "README.md"
homepage = ""
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9, <=3.11"
scikit-learn = "^1.0.2"
transformers = "^4.15.0"
matplotlib = "^3.5.1"
seaborn = "^0.11.2"
scipy = "^1.7.3"
optuna = "^2.10.0"
mlflow = "^1.22.0"
flake8 = "^4.0.1"
jupyter = "^1.0.0"
notebook = "^6.4.7"
black = "^21.12b0"
xgboost = "^1.5.1"
openpyxl = "^3.0.9"
hdbscan = "^0.8.27"
sentence-transformers = "^2.1.0"
plotly = "^5.5.0"
imbalanced-learn = "^0.9.0"
scikit-surprise = "^1.1.1"
statsmodels = "^0.13.1"
numpy = "1.22.0"
numba = "0.53"
torch = "1.10.1"
torchvision = "0.11.2"
torchaudio = "0.10.1"
lightgbm = "^3.3.2"
rouge-score = "^0.0.4"
datasets = "^1.17.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
