from typing import Any, Optional, Tuple

from beeline.propagation import PropagationContext, Request

def http_trace_parser_hook(request: Request) -> Optional[PropagationContext]: ...
def http_trace_propagation_hook(
    propagation_context: PropagationContext,
) -> Optional[dict[str, str]]: ...
def marshal_propagation_context(propagation_context: PropagationContext) -> str: ...
def unmarshal_propagation_context_with_dataset(
    trace_header: str,
) -> Tuple[Optional[str], Optional[str], Optional[dict[str, Any]], Optional[str]]: ...
