[tool.poetry]
name = "aiovk_new"
version = "0.0.1"
description = "A simple async library for vk with pydantic & httpx"
authors = ["Daniel Zakharov <daniel734@bk.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.21.3"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-asyncio = "^0.17.2"
bandit = "^1.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
