[tool.poetry]
name = "argumenttasks"
version = "0.1.0"
description = ""
authors = ["santiago"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "1.8.2"
PyYAML = "6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
