
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-20T15:01:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8afe1540b4e5f7fdeacff02af8a0c8a8dc30b2dc",
 "version": "0.14.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
