[tool.poetry]
name = "gitlab-ci-cd-variables-tree"
version = "0.1.0"
description = "Show Gitlab CI/CD variables as Tree structure"
authors = ["Fatih Sarhan <f9n@protonmail.com>"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://github.com/f9n/gitlab-ci-cd-variables-tree"
repository = "https://github.com/f9n/gitlab-ci-cd-variables-tree"

[tool.poetry.dependencies]
python = "^3.9"
python-gitlab = "^3.1.0"
rich = "^11.0.0"
click = "^8.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
gitlab-ci-cd-variables-tree = "gitlab_ci_cd_variables_tree.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
