[tool.poetry]
name = "deafadder-container"
version = "0.5.0"
description = "A dependency injection tools and container manager for python"
authors = ["Leddzip <leddzip@gmail.com>"]
keywords = ["component", "autowire", "DI", "singleton"]
readme = "README.rst"
license = "MIT"
homepage = "https://github.com/deaf-adder/deafadder-container"
repository = "https://github.com/deaf-adder/deafadder-container"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
coverage = "^6.1"
flake8 = "^4.0.1"
flake8-bugbear = "^21.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
