# Example JR2 config
robot:
  name: JR2
  action_type: continuous
  action_normalize: true
  proprio_obs:
    - eef_pos
    - eef_quat
    - arm_qpos_sin
    - arm_qpos_cos
  base_name: null
  scale: 1.0
  self_collision: false
  rendering_params: null
  assisted_grasping_mode: null
  controller_config:
    base:
      name: DifferentialDriveController
    arm:
      name: InverseKinematicsController
    gripper:
      name: NullGripperController