# Example Locobot config
robot:
  name: Locobot
  action_type: continuous
  action_normalize: true
  proprio_obs:
    - dd_base_lin_vel
    - dd_base_ang_vel
  base_name: null
  scale: 1.0
  self_collision: false
  rendering_params: null
  controller_config:
    base:
      name: DifferentialDriveController