[tool.poetry]
name = "flypper-redis"
version = "0.1.2"
description = "Feature flags, with a GUI - Redis backend"
documentation = "https://github.com/nicoolas25/flypper-redis"
repository = "https://github.com/nicoolas25/flypper-redis"
authors = ["Nicolas Zermati <nicoolas25@gmail.com>"]
readme = "README.md"
packages = [
  { include = "flypper_redis" },
  { include = "README.md" },
  { include = "LICENSE" },
]

[tool.poetry.dependencies]
python = "^3.7"
flypper = "^0.1.0"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.910"
types-redis = "^3.5.15"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
