
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-20T08:16:57+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d114f54db2348b26bebf3c9dad5fcbdab9057b4",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
