[tool.poetry]
name = "json-logger-stdout"
version = "1.0.0"
description = "JSON Logger for MicroServices. Prints logs to the stdout of the service and can be shipped to ES by leveraging a centralized tool like Fluentd"
authors = ["Chalukya J <chalukya@sentieo.com>"]

packages = [{ include = "json-logger-stdout" }]

[tool.poetry.dependencies]
python = "^3.6"
python-json-logger = "^2.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
