[tool.poetry]
name = "tf-restore-helper"
version = "0.1.1"
description = "Tf Restore Helper"
authors = ["Gary Hawker <dogfish@gmail.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/dogfish182/tf-restore-helper"
repository = "https://github.com/dogfish182/tf-restore-helper"
documentation = "https://tf-restore-helper.readthedocs.io"
classifiers = [
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[tool.poetry.urls]
Changelog = "https://github.com/dogfish182/tf-restore-helper/releases"

[tool.poetry.dependencies]
python = "^3.7.0"
click = ">=7,<9"
click-logging = "~1.0"
coloredlogs = "~15.0"
boto3 = ">=1.17,<1.21"
flatplan = "~1.3"


[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
moto = "^2.0.8"
werkzeug = "^2.0.2" # specific minimum requirement to pass safety check (moto dependency)
coverage = {extras = ["toml"], version = "^6.2"}
safety = "^1.10.3"
mypy = "^0.931"
typeguard = "^2.12.1"
xdoctest = {extras = ["colors"], version = "^0.15.4"}
sphinx = "^4.4.0"
sphinx-autobuild = "^2021.3.14"
pre-commit = "^2.13.0"
flake8 = "^3.9.2"
black = "^21.5b2"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^22.1.11"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.3"
pep8-naming = "^0.12.1"
darglint = "^1.8.0"
MarkupSafe = "^2.0"
reorder-python-imports = "^2.4.0"
pre-commit-hooks = "^4.0.1"
sphinx-rtd-theme = "^1.0.0"
sphinx-click = "^3.0.0"
Pygments = "^2.9.0"

[tool.poetry.scripts]
tf-restore-helper = "tf_restore_helper.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["tf_restore_helper"]

[tool.coverage.report]
show_missing = true
fail_under = 70

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
