[build-system]
requires = [
    "setuptools>=42",
    "wheel",
	"Faker==11.3.0",
	"py-postgresql==1.2.2",
	"python-dateutil==2.8.2",
	"six==1.16.0",
	"text-unidecode==1.3",
	"faker-vehicle==0.2.0",
	"tqdm==4.62.3",
]
build-backend = "setuptools.build_meta"