
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-17T13:17:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "29c75ed7b3e41bfd2f05ad02a10738e4d1efb9e9",
 "version": "0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
