CREATE USER _APP_USER_ IDENTIFIED BY _APP_PASS_
  DEFAULT TABLESPACE ECC_TAB01
  TEMPORARY TABLESPACE TEMP
/
GRANT CREATE SESSION TO _APP_USER_
/
GRANT QUERY REWRITE TO _APP_USER_
/
GRANT UNLIMITED TABLESPACE TO _APP_USER_
/
GRANT RESOURCE TO _APP_USER_
/
GRANT CONNECT TO _APP_USER_
/
GRANT SELECT_CATALOG_ROLE TO _APP_USER_
/
GRANT SELECT ANY DICTIONARY TO _APP_USER_
/
GRANT CREATE ANY DIRECTORY TO _APP_USER_
/
GRANT CREATE ANY SNAPSHOT TO _APP_USER_
/
GRANT CREATE ANY SYNONYM TO _APP_USER_
/
GRANT CREATE ANY view TO _APP_USER_
/
GRANT CREATE database link TO _APP_USER_
/
GRANT CREATE ANY CONTEXT TO _APP_USER_
/
GRANT CREATE JOB TO _APP_USER_
/
grant execute on DBMS_CRYPTO to _APP_USER_
/
grant execute on utl_file to _APP_USER_
/