CREATE USER _SEC_USER_ IDENTIFIED BY _SEC_PASS_
  DEFAULT TABLESPACE SEC_TAB01
  TEMPORARY TABLESPACE TEMP
/
GRANT CREATE SESSION TO _SEC_USER_
/
GRANT QUERY REWRITE TO _SEC_USER_
/
GRANT UNLIMITED TABLESPACE TO _SEC_USER_
/
GRANT RESOURCE TO _SEC_USER_
/
GRANT CONNECT TO _SEC_USER_
/
GRANT SELECT_CATALOG_ROLE TO _SEC_USER_
/
GRANT SELECT ANY DICTIONARY TO _SEC_USER_
/
GRANT CREATE ANY SNAPSHOT TO _SEC_USER_
/
GRANT CREATE ANY SYNONYM TO _SEC_USER_
/
GRANT CREATE ANY view TO _SEC_USER_
/
GRANT CREATE database link TO _SEC_USER_
/
GRANT CREATE ANY CONTEXT TO _SEC_USER_
/
grant execute on DBMS_CRYPTO to _SEC_USER_
/