CREATE TABLESPACE ECC_TAB01
DATAFILE '_TO_BE_CHANGED_ECC_TAB01_01' SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE ECC_TAB02
DATAFILE '_TO_BE_CHANGED_ECC_TAB02_01' SIZE 1M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE ECC_HIST_TAB01
DATAFILE '_TO_BE_CHANGED_ECC_HIST_TAB01_01' SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE ECC_IDX01
DATAFILE '_TO_BE_CHANGED_ECC_IDX01_01' SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE ECC_HIST_IDX01
DATAFILE '_TO_BE_CHANGED_ECC_HIST_IDX01_01' SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/


CREATE TABLESPACE ECC_HIST_LOB01
DATAFILE '_TO_BE_CHANGED_ECC_HIST_LOB01_01' SIZE 10M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 16K
/

CREATE TABLESPACE ECC_HIST_LOB02
DATAFILE '_TO_BE_CHANGED_ECC_HIST_LOB02_01' SIZE 1M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 16K
/

CREATE TABLESPACE ECC_HIST_LOB03
DATAFILE '_TO_BE_CHANGED_ECC_HIST_LOB03_01' SIZE 1M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 16K
/

CREATE TABLESPACE ECC_HIST_LOB04
DATAFILE '_TO_BE_CHANGED_ECC_HIST_LOB04_01' SIZE 1M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 16K
/

CREATE TABLESPACE ECC_LOB01
DATAFILE '_TO_BE_CHANGED_ECC_LOB01_01' SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 16K
/

CREATE TABLESPACE ECC_LOB02
DATAFILE '_TO_BE_CHANGED_ECC_LOB02_01' SIZE 1M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 16K
/

CREATE TABLESPACE ECC_INT_IDX01
DATAFILE '_TO_BE_CHANGED_ECC_INT_IDX01' SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE ECC_INT_TAB01
DATAFILE '_TO_BE_CHANGED_ECC_INT_TAB01' SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE ECC_LOG_IDX01
DATAFILE '_TO_BE_CHANGED_ECC_LOG_IDX01' SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
NOLOGGING
/
CREATE TABLESPACE ECC_LOG_TAB01
DATAFILE '_TO_BE_CHANGED_ECC_LOG_TAB01' SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/



-------------------------------------------------------------------------



CREATE TABLESPACE SEC_IDX01 DATAFILE
  '_TO_BE_CHANGED_SEC_IDX01' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
DEFAULT
  NO INMEMORY
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SEC_LOG_TAB01 DATAFILE
  '_TO_BE_CHANGED_SEC_LOG_TAB01' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
DEFAULT
  NO INMEMORY
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SEC_MASS_IDX01 DATAFILE
  '_TO_BE_CHANGED_SEC_MASS_IDX01' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
DEFAULT
  NO INMEMORY
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SEC_MASS_TAB01 DATAFILE
  '_TO_BE_CHANGED_SEC_MASS_TAB01' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
DEFAULT
  NO INMEMORY
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SEC_TAB01 DATAFILE
  '_TO_BE_CHANGED_SEC_TAB01' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
DEFAULT
  NO INMEMORY
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;