[build-system]
requires = [
    "setuptools>=49.2.1",
    "lmfit>=1.0.3",
    "numba>=0.54.1",
    "numpy>=1.20.3",
    "ome_types>=0.2.9",
    "opencv_python>=4.5.3.56",
    "pyqode.python>=2.12.1",
    "PyQt5>=5.15.6",
    "pyqtgraph>=0.12.2",
    "pyueye>=4.90.0.0",
    "QDarkStyle>=3.0.2",
    "scipy>=1.7.1",
    "tifffile>=2021.8.30"
]
build-backend = "setuptools.build_meta"