
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-20T08:32:38-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "25f8c2f66c46572c778cffc1f29ce2cce23ca4ab",
 "version": "2.8.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
