
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-20T00:21:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2ba2eea7904d0753f7582ed75e98fb3c6e8fe57",
 "version": "1.35.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
