[build-system]
requires = [
         "flit_core >=2,<4",
         ]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "histomics_stream"
author = "Lee Newberg"
author-email = "lee.newberg@kitware.com"
home-page = "https://github.com/DigitalSlideArchive/histomics_stream"
requires = [
         "imagecodecs",
         "itk",
         "napari_lazy_openslide",
         "openslide-python",
         "pillow",
         "tensorflow>=2.6.0,<2.7",
         "tifffile",
         "zarr",
         ]
description-file = "README.md"
classifiers = ["License :: OSI Approved :: Apache Software License"]
