
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-19T14:35:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d4e29cd7d2f9d4a0580d1f8497b1d00f59d3c14",
 "version": "0.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
