[tool.poetry]
authors = ["CoSphere Tech <contact@cosphere.org>"]
classifiers = ["Topic :: Software Development :: Libraries :: Python Modules"]
description = "Szczypiorek environment management for humans."
keywords = ["szczypiorek", "environment", "secrets"]
name = "szczypiorek"
readme = "README.md"
repository = "https://github.com/cosphere-org/szczypiorek"
version = "1.1.3"

[tool.poetry.scripts]
szczypiorek = "szczypiorek.cli:cli"

[tool.poetry.dependencies]
PyYAML = "^6.0"
bash = "^0.6"
click = "^8.0.3"
python = "~3.9.9"
python-gnupg = "^0.4.8"
validators = "^0.18.2"

[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"
fake-factory = "^0.7.4"
flake8 = "^4.0.1"
flake8-docstrings = "^1.6.0"
ipdb = "^0.13.9"
pep8-naming = "^0.12.1"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-mock = "^3.6.1"
pytest-pythonpath = "^0.7.3"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
