data_files:
    mc:
        train_sample:
            magic1:
                input_mask: "../../../MCs/MAGIC/ST.03.07/za05to35/Train_sample/1.Calibrated/GA_M1*root"
                hillas_output: "../../../MCs/MAGIC/ST.03.07/za05to35/Train_sample/2.Hillas/iv_hillas_m1.h5"
            magic2:
                input_mask: "../../../MCs/MAGIC/ST.03.07/za05to35/Train_sample/1.Calibrated/GA_M2*root"
                hillas_output: "../../../MCs/MAGIC/ST.03.07/za05to35/Train_sample/2.Hillas/iv_hillas_m2.h5"
                
        test_sample:
            magic1:
                input_mask: "../../../MCs/MAGIC/ST.03.07/za05to35/Test_sample/1.Calibrated/GA_M1*root"
                hillas_output: "../../../MCs/MAGIC/ST.03.07/za05to35/Test_sample/2.Hillas/iv_hillas_m1.h5"
                reco_output: "../../../MCs/MAGIC/ST.03.07/za05to35/Test_sample/3.Reco/iv_reco_m1.h5"
            magic2:
                input_mask: "../../../MCs/MAGIC/ST.03.07/za05to35/Test_sample/1.Calibrated/GA_M2*root"
                hillas_output: "../../../MCs/MAGIC/ST.03.07/za05to35/Test_sample/2.Hillas/iv_hillas_m2.h5"
                reco_output: "../../../MCs/MAGIC/ST.03.07/za05to35/Test_sample/3.Reco/iv_reco_m2.h5"
                
    data:
       train_sample:
           magic1:
               input_mask: "../../../Data/MAGIC/Off/Train_sample/1.Calibrated/20*_M1_*root"
               hillas_output: "../../../Data/MAGIC/Off/Train_sample/2.Hillas/iv_hillas_m1.h5"
           magic2:
               input_mask: "../../../Data/MAGIC/Off/Train_sample/1.Calibrated/20*_M2_*root"
               hillas_output: "../../../Data/MAGIC/Off/Train_sample/2.Hillas/iv_hillas_m2.h5"
               
       test_sample:
           magic1:
               input_mask: "../../../Data/MAGIC/CrabNebula/1.Calibrated/20*_M1_*root"
               hillas_output: "../../../Data/MAGIC/CrabNebula/ctapipe/2.Hillas/iv_hillas_m1.h5"
               reco_output: "../../../Data/MAGIC/CrabNebula/ctapipe/3.Reco/reco_m1.h5"
           magic2:
               input_mask: "../../../Data/MAGIC/CrabNebula/1.Calibrated/20*_M2_*root"
               hillas_output: "../../../Data/MAGIC/CrabNebula/ctapipe/2.Hillas/iv_hillas_m2.h5"
               reco_output: "../../../Data/MAGIC/CrabNebula/ctapipe/3.Reco/reco_m2.h5"

image_cleaning:
    magic:
        picture_thresh: 6
        boundary_thresh: 3.5
        min_number_picture_neighbors: 1
        # 1.5 slices x 1.64 GHz
        max_time_diff: 2.46
        # 4.5 slices x 1.64 GHz
        max_time_off: 7.38
        min_number_neighbors: 3
        usetime : True
        usesum : True
        findhotpixels : True

bad_pixels:
    magic:
        pedestalLevel: 400
        pedestalLevelVariance: 4.5
        pedestalType: "FromExtractorRndm"

energy_rf:
    save_name: "RFs/energy_rf.joblib"
    cuts: "(event_id > 0) & (multiplicity > 1) & (intensity > 30) & (length > 0.0) & (intensity_width_1 < 0.15)"
    settings:
        n_estimators: 100
        min_samples_leaf: 10
        n_jobs: 3
    
    features:
        ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'intensity_width_1', 'intensity_width_2']

direction_rf:
    save_name: "RFs/direction_rf.joblib"
    cuts: "(event_id > 0) & (multiplicity > 1) & (intensity > 30) & (length > 0.0) & (intensity_width_1 < 0.15)"
    settings:
        n_estimators: 100
        min_samples_leaf: 10
        n_jobs: 3
    
    features:
        'disp': ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi']
        'pos_angle_shift': ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi']

classifier_rf:
    save_name: "RFs/classifier_rf.joblib"
    cuts: "(event_id > 0) & (multiplicity > 1) & (intensity > 30) & (length > 0.0) & (intensity_width_1 < 0.15)"
    settings:
        n_estimators: 100
        min_samples_leaf: 10
        n_jobs: 3
    
    features:
        ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'n_islands']

irf:
    output_name: "/path/to/IRF_file/outfile.fits"

source:
    name: "Crab"
    coordinates:
        ra_dec: [83.633083, 22.0145]

event_list:
    output_directory: "/path/to/output/directory"
    max_time_diff: 6.9e-4
    cuts:
        quality:
            l3rate: "80 < value < 1000"
            dc: "0 < value < 7e3"
        selection:
            "(event_id > 0) & (multiplicity > 1) & (abs(pos_angle_shift_reco - 0.5) > 0.4) & (event_class_0 > 0.8)"

spectrum:
    input_files: "/path/to/input/events*.fits"
    energy_reco_nbins: 30
    energy_reco_min: 0.005  # TeV
    energy_reco_max: 50.    # TeV
    energy_true_factor: 1.4      # ratio of number of estimated-to-true energy bins
    off_positions: 3
    #exclude_region: {0 : [183.604, -8.708, 0.5]}
    spectral_model:
        power_law: {'index' : 2, 'amplitude' : 2.0e-11, 'reference' : 0.3}
        #log_parabola: {'alpha' : 2, 'amplitude' : 2.0e-11, 'beta' : 0.2, 'reference' : 0.3}
