[tool.poetry]
name = "sphinx-github-changelog"
version = "1.2.0"
description = "Build a sphinx changelog from GitHub Releases"
authors = ["Joachim Jablon <ewjoachim@gmail.com>"]
license = "MIT"
classifiers = [
    "Topic :: Documentation",
    "Topic :: Documentation :: Sphinx",
    "Framework :: Sphinx",
    "Framework :: Sphinx :: Extension",
]
readme = "README.rst"
keywords = ["sphinx", "github", "releases", "changelog"]
homepage = "https://sphinx-github-changelog.readthedocs.io/en/latest/"
repository = "https://github.com/ewjoachim/sphinx-github-changelog"
documentation = "https://sphinx-github-changelog.readthedocs.io/en/latest/"

[tool.poetry.dependencies]
python = "^3.7"
docutils = "*"
importlib-metadata = {version = "*", python = "<3.8"}
requests = "*"
Sphinx = "*"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
check-manifest = "^0.46"
doc8 = "^0.8.1"
flake8 = "^3.9.1"
isort = "^5.8.0"
mypy = "^0.812"
pytest = "^6.2.3"
pytest-cov = "^2.11.1"
pytest-mock = "^3.5.1"
requests-mock = "^1.8.0"
sphinx-rtd-theme = "^0.5.2"
tox = "^3.23.0"
pre-commit = "^2.12.0"
dunamai = "^1.5.4"
types-requests = "^2.25.0"
types-docutils = "^0.1.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
