
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-19T07:02:29+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "19fc4d436484684cf15642f4c65df388aedd175f",
 "version": "0.24.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
