[build-system]
requires = [ "flit_core >=3.2,<4" ]
build-backend = "flit_core.buildapi"

[project]
name = "formbox"
version = "0.4.1"
description = "Format mbox as HTML/XML"
readme = "README.md"
requires-python = ">=3.6"
license = { file = "COPYING" }
authors = [ { name = "Nguyễn Gia Phong", email = "mcsinyx@disroot.org" } ]
maintainers = [ { name = "Nguyễn Gia Phong", email = "mcsinyx@disroot.org" } ]
keywords = [ "email", "format", "html", "mbox", "template", "xml" ]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Communications :: Email",
    "Topic :: Utilities" ]
dependencies = [ "bleach", "markdown" ]
urls = { SourceHut = "https://sr.ht/~cnx/formbox" }
scripts = { formbox = "formbox:main" }
