[tool.poetry]
name = "gramadan-py"
version = "0.1.1"
description = "Pure Python implementation of michmech's C# Gramadán utility for manipulating the Irish National Morphology Database"
authors = ["Phil Weir (Python conversion Michal Měchura's work) <phil.t.weir@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "gramadan" },
    { include = "gramadan/v2" }
]

[tool.poetry.dependencies]
python = "^3.9"
lxml = "^4.7.1"
tabulate = "^0.8.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
lxml-stubs = "^0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
