[tool.poetry]
name = "cloops"
version = "0.0.6"
description = "dfdfgdfg"
authors = ["Your Name <you@example.com>"]
license = "dfgdfgdg"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
