[tool.poetry]
name = "craftr-dsl"
version = "0.7.1"
description = "Domain specific language for the Craftr build system."
authors = ["Niklas Rosenstein <rosensteinniklas@gmail.com>"]
license = "MIT"
readme = "readme.md"
packages = [
  { include = "craftr/dsl", from="src" }
]

[tool.poetry.dependencies]
python = "^3.10"
"nr.util" = "^0.4.0"
astor = "^0.8.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
