[tool.poetry]
name = "jps_algo"
version = "0.1.1"
description = "Jackson's Preemptive Scheduleを解くためのアルゴリズムが実装されている"
repository = "https://github.com/tkp0331/jps-algo"
authors = ["鈴木貴大 <merioda.seven.24@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
