[tool.poetry]
name = "wxnotify"
version = "0.1.0"
description = ""
authors = ["yovafeng <64761294@qq.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Django = "3.2.5"
celery = "4.4.0"
redis = "3.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
