
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-19T14:50:37-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "81175efae08c3149e89982b83ec6d1e084d48827",
 "version": "2.0a9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
