[tool.poetry]
name = "repl_python3_Discode"
version = "0.1.0"
description = ""
authors = ["TheKungFuChuck <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.4"
websockets = "^10.1"
Sphinx = "^4.3.1"
furo = "^2021.11.23"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
