
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-18T10:38:53-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "240827cf98db436d99b41dde2a642f256c4332d5",
 "version": "2.3.5.dev20220119"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
