"""
**Real** `Optional` type in `python`, not `@Nullable` annotation.

Home: https://baijifeilong.github.io/2022/01/09/ice-spring-real-optional/index.html

Github: https://github.com/baijifeilong/IceSpringRealOptional

PyPI: https://pypi.org/project/IceSpringRealOptional

Generated by BaiJiFeiLong@gmail.com

License: MIT
"""

# Created by BaiJiFeiLong@gmail.com at 2022/1/9 18:21
