"""
**Real** `Optional` type in `python`, not `@Nullable` annotation.

Home: https://baijifeilong.github.io/2022/01/09/ice-spring-real-optional/index.html

Github: https://github.com/baijifeilong/IceSpringRealOptional

PyPI: https://pypi.org/project/IceSpringRealOptional

Generated by BaiJiFeiLong@gmail.com

License: MIT
"""

# Created by BaiJiFeiLong@gmail.com at 2022/1/10 11:16

from __future__ import annotations

from typing import Type, Any

from IceSpringRealOptional.generics import T


class TypingUtils(object):
    @staticmethod
    def gg(value, _type: Type[T] = Any) -> T:
        return value

    @staticmethod
    def unused(*args) -> None:
        pass


gg = TypingUtils.gg
unused = TypingUtils.unused
