
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-13T13:10:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5cb79a84536b720238efdc0b1005bd0e42f73f09",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
