
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-21T10:39:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "20dd378507ce299805a86515a776bbb07b3fa210",
 "version": "2022.01.20.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
