[tool.poetry]
name = "pepe-qrcode-cli"
version = "0.3.0"
description = "QRCode CLI for generating simple QR codes"
authors = ["Pepe <pimanroya06@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
pepe-qrcode-cli = "pepe_qrcode_cli.main:app"

[tool.poetry.dependencies]
python = "^3.7"
typer = {extras = ["all"], version = "^0.4.0"}
qrcode = "^7.3.1"
pyzbar = "^0.1.8"
Pillow = "^9.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
