[dependencies.lib0]
path = "local_dependencies/lib0"

[dependencies.pyo3]
features = ["extension-module"]
version = "0.14.5"

[dependencies.yrs]
path = "local_dependencies/yrs"

[lib]
crate-type = ["cdylib"]
name = "y_py"

[package]
authors = ["Pierre-Olivier Simonard <pierre.olivier.simonard@gmail.com>", "Kevin Jahns <kevin.jahns@protonmail.com>", "John Waidhofer <waidhoferj@gmail.com>"]
edition = "2018"
name = "y-py"
version = "0.2.2"
