
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-22T12:51:11-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "835543160864cdbd06b9f82dd0e18de010627e97",
 "version": "3.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
