[tool.poetry]
name = "dotwarden"
version = "1.0.4"
description = "a utility for generating hidden random . directories"
authors = ["Jaffar <jaffar.almaleki@gmail.com>"]
homepage = "https://github.com/JaffarA/dotwarden"
repository = "https://github.com/JaffarA/dotwarden"
readme = "README.md"
license = "GPLv3"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
