import os

TWITTER_CONSUMER_KEY        = os.getenv('TWITTER_CONSUMER_KEY')
TWITTER_CONSUMER_SECRET     = os.getenv('TWITTER_CONSUMER_SECRET')
# TWITTER_BEARER_TOKEN        = os.getenv('TWITTER_BEARER_TOKEN')
TWITTER_ACCESS_TOKEN        = os.getenv('TWITTER_ACCESS_TOKEN')
TWITTER_ACCESS_TOKEN_SECRET = os.getenv('TWITTER_ACCESS_TOKEN_SECRET')

AZURE_CONNECTION_STRING     = os.getenv('AZURE_CONNECTION_STRING')
