---
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/ci.yml
      - "src/**"
      - "tests/**"
      - setup.cfg
  workflow_dispatch:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    env:
      USING_COVERAGE: '3.9'

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r dev-requirements.txt

      - name: "Install project"
        run: |
          python -m pip install .

      - name: "Run tests"
        run: |
          python -m pip install .
          python -X dev -m pytest tests --cov --cov-report xml -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
