# Generated by Django 2.1.3 on 2019-12-02 18:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('success', models.BooleanField(null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('data', models.TextField(null=True)),
                ('traceback', models.TextField(null=True)),
            ],
        ),
    ]
