# Generated by Django 3.0.8 on 2020-08-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kiwi', '0002_task_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-start_time',)},
        ),
    ]
