
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-23T21:35:02+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7ad18e6db7c733084066c67d5a819bac3b9636e",
 "version": "1.31.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
