[tool.poetry]
name = "UUIDTools"
version = "0.1.1"
description = "Utility for find, extract, exchange and permutate uuids in string and pandas series"
authors = ["Pablo Ruiz <pablo.ruiz@imogate.eu>"]
license = "MIT"
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.9"
uuid = "^1.30"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
# genuuid = 'generate uuid'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
