
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-19T17:40:17+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "10478442b5b3b7844e379d090bd6cc7b5ff49e50",
 "version": "0.0.72"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
