
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-24T14:26:26-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "52b280b35cf8dcca55e1f124cbe65003aeee0ba6",
 "version": "0.8.373"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
