[tool.poetry]
name = "edr-agent-validator"
version = "0.1.0"
description = "The Red Canary EDR validation tool."
authors = ["Andrew Kennedy <andrewk36@gmail.com>"]
homepage = "https://github.com/andrew-kennedy/edr-agent-validator"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
psutil = "^5.9.0"
desert = "^2020.11.18"
marshmallow = "^3.14.1"
typer = "^0.4.0"
marshmallow-enum = "^1.5.1"

[tool.poetry.scripts]
edr-agent-validator = "edr_agent_validator.console:app"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^4.0.1"
black = { version = "^21.12b0", allow-prereleases = true }
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.3"
flake8-bugbear = "^22.1.11"

[tool.pyright]
reportUnknownMemberType = "information"

[tool.black]
line-length = 80
target-version = ['py310']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
