
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: envoy.base.checker:package

from setuptools import setup

setup(**{
    'author': 'Ryan Northey',
    'author_email': 'ryan@synca.io',
    'description': '"Checker definitions used in Envoy proxy\'s CI"',
    'install_requires': (
        'abstracts>=0.0.12',
        'envoy.base.runner>=0.1.1',
    ),
    'license': 'Apache Software License 2.0',
    'long_description': """
envoy.base.checker
==================

Checker definitions used in Envoy proxy's CI
""",
    'maintainer': 'Ryan Northey',
    'maintainer_email': 'ryan@synca.io',
    'name': 'envoy.base.checker',
    'namespace_packages': (
    ),
    'package_data': {
        'envoy.base.checker': (
            'py.typed',
        ),
    },
    'packages': (
        'envoy.base.checker',
    ),
    'url': 'https://github.com/envoyproxy/pytooling/tree/main/envoy.base.checker',
    'version': '0.1.2',
})
