import os

TWITTER_CONSUMER_KEY        = os.environ['TWITTER_CONSUMER_KEY']
TWITTER_CONSUMER_SECRET     = os.environ['TWITTER_CONSUMER_SECRET']
# TWITTER_BEARER_TOKEN        = os.environ['TWITTER_BEARER_TOKEN']
TWITTER_ACCESS_TOKEN        = os.environ['TWITTER_ACCESS_TOKEN']
TWITTER_ACCESS_TOKEN_SECRET = os.environ['TWITTER_ACCESS_TOKEN_SECRET']

AZURE_CONNECTION_STRING     = os.environ['AZURE_CONNECTION_STRING']
