[[bench]]
harness = false
name = "benches"

[dependencies]
wasm-bindgen = "0.2"

[dependencies.lib0]
path = "../lib0"

[dependencies.rand]
features = ["wasm-bindgen"]
version = "0.7.0"

[dependencies.smallstr]
features = ["union"]
version = "0.2"

[dev-dependencies]
criterion = "0.3"

[lib]
bench = true
doc = true
doctest = true

[package]
authors = ["Kevin Jahns <kevin.jahns@pm.me>", "Bartosz Sypytkowski <b.sypytkowski@gmail.com>"]
description = "High performance implementation of the Yjs CRDT"
edition = "2018"
homepage = "https://github.com/yjs/yrs/"
keywords = ["crdt", "yrs"]
license = "MIT"
name = "yrs"
readme = "./README.md"
repository = "https://github.com/yjs/yrs/"
version = "0.2.1"
