[tool.poetry]
name = "sylte"
version = "0.0.1"
description = "Pickling and unpickling of function arguments"
readme = "README.md"
repository = "https://github.com/danhje/sylte"
homepage = "https://github.com/danhje/sylte"
authors = ["Daniel Hjertholm <daniel.hjertholm@icloud.com>"]
license = "MIT"
keywords = ["pickle", "pickling", "arguments", "debug", "cache"]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers",
    "Natural Language :: English"
]

[tool.poetry.dependencies]
python = ">=3.7, <3.11"
appdirs = "^1.4.4"

[tool.poetry.dev-dependencies]
pytest = "*"
pre-commit = "^2.16.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
