[tool.poetry]
name = "tws_simple_package"
version = "0.1.1"
description = "Simple Poetry Package"
authors = ["Taylor Santiago <tsanti928@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
jsonschema = "^4.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
tws_simple_package = "tws_simple_package.tws_simple_package:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
