
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-23T14:37:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc9f3dabb17c175f904e0aa70399ca5d5e77e81f",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
