[tool.poetry]
name = "cas_client"
version = "0.1.0"
description = ""
authors = ["Amin Jamal <a.jamal@greyrook.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
twine = "^3.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
