[tool.poetry]
name = "pytest-datadir-mgr"
version = "1.3.1"
description = "Manager for test data: downloads, artifact caching, and a tmpdir context."
authors = ["Joel Berendzen <joel@generisbio.com>"]
license = "BSD-3-Clause"
readme = "README.rst"
homepage = "https://github.com/joelb123/pytest-datadir-mgr"
keywords = [
    "testing",
    "pytest-plugins",
    "downloads",
    "data manager",
    "test data",
    "software engineering"
    ]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Plugins",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Framework :: Pytest"
    ]

[tool.poetry.urls]
Changelog = "https://github.com/joelb123/svante/releases"

[tool.poetry.dependencies]
python = "^3.7.1,<4.0.0"
progressbar2 = "*"
pytest = "*"
requests_download = "*"

[tool.poetry.dev-dependencies]
coverage = {extras = ["toml"], version = "*"}
black = "*"
nox = "*"
pylint = "*"
pytest-cov = "*"
Sphinx = "*"
nox-poetry = "*"
safety = "*"
mypy = "*"
typeguard = "*"
xdoctest = {extras = ["colors"], version = "*"}
sphinx-autobuild = "*"
pre-commit = "*"
flake8 = "*"
flake8-bandit = "*"
flake8-bugbear = "*"
flake8-docstrings = "*"
pep8-naming = "*"
darglint = "*"
reorder-python-imports = "*"
pre-commit-hooks = "*"
sphinx-rtd-theme = "*"
Pygments = "*"

[tool.poetry.plugins]
pytest11 = { datadir_mgr = "pytest_datadir_mgr" }

[tool.black]
line-length = 79
target-version = ['py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
  \.git
  | \.mypy_cache
  | \.nox
  | \.idea
  | \.pytest-cache
  | _build
  | build
  | dist
  | tests/
)/
'''

[tool.coverage.run]
omit = ["tests/*", "noxfile.py", ".nox/*"]

[tool.coverage.report]
exclude_lines = [
    "if self.debug:",
    "pragma: no cover",
    "raise NotImplementedError",
    "if __name__ == .__main__.:"
    ]


[tool.pylint.'MESSAGES CONTROL']
disable = """,
   print-statement,
   parameter-unpacking,
   unpacking-in-except,
   old-raise-syntax,
   backtick,
   long-suffix,
   old-ne-operator,
   old-octal-literal,
   import-star-module-level,
   non-ascii-bytes-literal,
   raw-checker-failed,
   bad-inline-option,
   locally-disabled,
   file-ignored,
   suppressed-message,
   useless-suppression,
   deprecated-pragma,
   use-symbolic-message-instead,
   apply-builtin,
   basestring-builtin,
   buffer-builtin,
   cmp-builtin,
   coerce-builtin,
   execfile-builtin,
   file-builtin,
   long-builtin,
   raw_input-builtin,
   reduce-builtin,
   standarderror-builtin,
   unicode-builtin,
   xrange-builtin,
   coerce-method,
   delslice-method,
   getslice-method,
   setslice-method,
   no-absolute-import,
   old-division,
   dict-iter-method,
   dict-view-method,
   next-method-called,
   metaclass-assignment,
   indexing-exception,
   raising-string,
   reload-builtin,
   oct-method,
   hex-method,
   nonzero-method,
   cmp-method,
   input-builtin,
   round-builtin,
   intern-builtin,
   unichr-builtin,
   map-builtin-not-iterating,
   zip-builtin-not-iterating,
   range-builtin-not-iterating,
   filter-builtin-not-iterating,
   using-cmp-argument,
   eq-without-hash,
   div-method,
   idiv-method,
   rdiv-method,
   exception-message-attribute,
   invalid-str-codec,
   sys-max-int,
   bad-python3-import,
   deprecated-string-function,
   deprecated-str-translate-call,
   deprecated-itertools-function,
   deprecated-types-field,
   next-method-defined,
   dict-items-not-iterating,
   dict-keys-not-iterating,
   dict-values-not-iterating,
   deprecated-operator-function,
   deprecated-urllib-function,
   xreadlines-attribute,
   deprecated-sys-function,
   exception-escape,
   comprehension-escape,
   no-self-use,
   wrong-import-position,
   bad-continuation,
   too-many-locals,
   too-many-statements,
   too-few-public-methods,
   too-many-arguments,
   too-many-branches,
   too-many-instance-attributes,
   pointless-statement,
   invalid-name,
   consider-using-in,
   """

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.masonry.api"
