[tool.poetry]
name = "shui"
version = "0.5.0"
description = "Spark-Hadoop Unix Installer"
license = "MIT"
authors = ["James Robinson <james.em.robinson@gmail.com>"]
readme = "README.md"
repository = "https://github.com/jemrobinson/shui"
keywords = ["Spark", "Hadoop", "installation"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "Natural Language :: English",
    "Operating System :: Unix",
    "Topic :: Software Development",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = "^3.6"
beautifulsoup4 = "^4"
cleo = "^0.8"
packaging = "^20.9"
pathlib3x = "^1.3"
requests = "^2.25"
tqdm = "^4.59"
url-normalize = "^1.4"
urllib3 = "^1.26"

[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}
pylint = "^2.7"

[tool.poetry.scripts]
shui = "shui.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
