[tool.poetry]
name = "incolumepy.singleton_decorator"
version = "1.2.0"
description = ""
authors = ["Britodfbr <britodfbr@gmail.com>"]
packages = [
  {include="incolumepy/singleton_decorator", from=""},
]
[tool.poetry.dependencies]
python = ">=3.6,<4"

[tool.poetry.dev-dependencies]
tox = "^3.24.5"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
mypy = "^0.931"
types-toml = "^0.10.3"
isort = "5.8.0"
pylint = "2.10.0"
black = [
  {version="20.8b0", python="~3.6"},
  {version="21.12b0", python="^3.7"},
]
pydocstyle = "^6.1.1"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--cov=incolumepy"
testpaths = [
  "tests",
]

[PEP8]
# define para todos os linters compatíveis
max-line-length = 120

[flake8]
max-line-length = 120

[tool.pylint.format]
# Maximum number of characters on a single line.
max-line-length = 120

[tool.pylint.basic]
# Allow shorter and longer variable names than the default.
argument-rgx = "[a-z_][a-z0-9_]*$"
attr-rgx = "[a-z_][a-z0-9_]*$"
variable-rgx = "[a-z_][a-z0-9_]*$"

# Ensure that orjson is analysed as a C extension by pylint.
extension-pkg-whitelist = "orjson"

[tool.pylint.messages_control]
disable = [
    # Disable too many and too few checks.
    "too-many-ancestors",
    "too-many-arguments",
    "too-many-boolean-expressions",
    "too-many-branches",
    "too-many-function-args",
    "too-many-instance-attributes",
    "too-many-lines",
    "too-many-locals",
    "too-many-nested-blocks",
    "too-many-public-methods",
    "too-many-return-statements",
    "too-many-statements",
    "too-few-public-methods",

    # Similar lines in files (often the case in tests).
    "duplicate-code",

    # Many functions (e.g. callbacks) will naturally have unused arguments.
    "unused-argument",

    # Disable checking that method could be a function in classes (often used for organisation).
    "no-self-use",

    # Disable failure for TODO items in the codebase (code will always have TODOs).
    "fixme",

    # Disable docstrings checks as we don't require excessive documentation.
    "missing-docstring",

    "no-member",
    "unspecified-encoding",
]

[tool.mypy]
mypy_path = "incolumepy"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.isort]
multi_line_output = 3
#line_length = 120
include_trailing_comma = true

[tool.black]
#line_length = 120

[tool.tox]
legacy_tox_ini = """
[tox]
minversion = 3.3.0
isolated_build = True
envlist =
    black
    flake8
    isort
    mypy
    pydocstyle
    pylint
    py{36,37,38,39,310}

;[tox:.package]
;basepython = python3

[testenv]
setenv = LANG=pt_BR.UTF-8
whitelist_externals = poetry
skip_install = true
commands =
    poetry env use {envpython}
    poetry install -vv --no-root
    poetry run pytest {posargs} tests/

[testenv:pycodestyle]
#max_line_length = 120

[testenv:mccabe]
max_complexity = 5

[testenv:flake8]
deps = flake8
max-complexity = 10
commands = poetry run flake8 --config pyproject.toml incolumepy/ tests/

[testenv:mypy]
deps =
    mypy
    types-toml
commands = mypy incolumepy/

[testenv:pydocstyle]
commands = poetry run pydocstyle incolumepy/ tests/

[testenv:isort]
commands = poetry run isort --check --atomic --py all incolumepy/ tests/

[testenv:pylint]
commands = poetry run pylint incolumepy/ tests/

[testenv:black]
commands = poetry run black --check incolumepy/ tests/
"""
