[tool.poetry]
name = "xawsprofile"
version = "0.2.4"
description = "AWS profile utility"
readme = "README.md"
authors = ["Daniel Clayton <dclayton@godaddy.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "<4,>=3.6.1"
click = ">=8.0.1"
boto3 = "^1.20.33"

[tool.poetry.dev-dependencies]
pytest = ">=6.2.4"
dephell = ">=0.8.3"

[tool.poetry.scripts]
awsprofile = "xawsprofile.cli:main"

[build-system]
requires = ["setuptools", "poetry>=1.1.6"]
build-backend = "poetry.masonry.api"

