from .extra import *


def force_sudo_password_promt() -> None: ...
def get_root_privileges() -> bool: ...
def get_root_privileges_or_exit(exit_code: int) -> None: ...
def has_root_privileges() -> bool: ...
