[tool.poetry]
name = "aim-build"
version = "0.1.38"
description = "A build tool for C++."
authors = ["David Walker <diwalkerdev@twitter.com>"]
license = "MPL 2.0"
readme = "README.md"
homepage = "https://github.com/diwalkerdev/Aim"
repository = "https://github.com/diwalkerdev/Aim"
keywords = ["cpp", "build-tool", "poetry", "python", "linux", "windows"]
include = ["aim_build/LICENSE", "aim_build/zipdemo.zip"]
classifiers = [
	"Development Status :: 3 - Alpha",
	"Environment :: Console",
	"Intended Audience :: Developers", 
	"Intended Audience :: End Users/Desktop",
	"License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
	"Operating System :: OS Independent",
	"Programming Language :: Python :: 3.7",
	"Programming Language :: Python :: 3.8",
	"Programming Language :: Python :: 3.9",
	"Topic :: Software Development :: Build Tools",
]

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.0"
cerberus = "^1.3"
ninja-syntax = "^1.7"
tabulate = "^0.8.7"
ninja = "^1.10.2"
ninja_syntax = "^1.7.2"

[tool.poetry.dev-dependencies]
pre-commit = "^2.6.0"
black = "^19.10b0"
pylint = "^2.5.3"
pylint-exit = "^1.2.0"

[tool.poetry.scripts]
aim = "aim_build.main:entry"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

