[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "eatlocal"
authors = [{name = "Russell Helmstedter", email = "rhelmstedter@gmail.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = ["selenium==4.1.0", "python-dotenv==0.19.2"]

[project.urls]
Home = "https://github.com/rhelmstedter/eatlocal"

[project.scripts]
eatlocal = "eatlocal.__main__:main"
