[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "scverse"
author = "Danila Bredikhin"
author-email = "danila.bredikhin@embl.de"
description-file = "README.md"
home-page = "https://github.com/gtca/scverse"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Intended Audience :: Science/Research"
]
requires-python = ">= 3.7"
requires = [
    "anndata",
    "scanpy",
    "mudata",
    "muon",
]

[tool.flit.metadata.requires-extra]
docs = [
    "sphinx >= 4.0",
    "sphinx-rtd-theme",
    "readthedocs-sphinx-search",
    "nbsphinx",
    "sphinx_automodapi"
]
atac = [
    "pybedtools",
    "pysam"
]

[tool.flit.metadata.urls]
Documentation = "https://scverse.org/"

[tool.flit.sdist]
exclude = [".github", "docs/build"]

[tool.black]
line-length = 100
target-version = ['py37']

