[tool.poetry]
authors = ["niwla23 <alwin@cloudserver.click>"]
description = "This Scrapper can get data from iserv servers hosting Untis plans. (Common in germany)"
license = "MIT"
name = "iservscrapping"
version = "6.0.0"

packages = [
  {include = "iservscrapping"},
]

[tool.poetry.dependencies]
Markdown = "^3.3.6"
beautifulsoup4 = "^4.10.0"
lxml = "^4.7.1"
python = ">=3.7,<4.0"
requests = "^2.27.1"
requests-cache = "^0.9.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
python-dotenv = "^0.19.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
