name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: |
        curl -L -o ta-lib-0.4.0-src.tar.gz  http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz &&
        tar xvfz ta-lib-0.4.0-src.tar.gz &&
        cd ta-lib &&
        ./configure &&
        sudo make &&
        sudo make install &&
        sudo ldconfig
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install -e .[dev]
    - name: Lint with flake8
      run: |
        flake8 app tests
    - name: format with black
      run: |
        black --check -l 120 app tests
    - name: ingest stock data
      run: | 
        python -m app.data_bundle
    - name: Test with pytest
      run: |
        python -m pytest --cov=./ --cov-report=xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true