[tool.poetry]
name = "deepdog"
version = "0.1.0"
description = ""
authors = ["Deepak Mallubhotla <dmallubhotla+github@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
pytest-cov = "^3.0.0"
mypy = "^0.931"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
