[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pandas_dataframe_convert"
authors = [{name = "Doug Ransom", email = "doug@ransom.vip"}]
classifiers = ["License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Topic :: Scientific/Engineering"]
dynamic = ["version", "description"]
dependencies  = ['flit','pandas']
readme = "readme.md"
[project.urls]
source="https://github.com/dougransom/pandas_dataframe_convert"
[project.scripts]
dataframe_convert="pandas_dataframe_convert.dataframe_convert:main"