[tool.poetry]
authors = ["Guillaume Gauvrit <guillaume@gauvr.it>"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Framework :: Pyramid",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Internet :: WWW/HTTP",
]
description = "Pyramid Bindings for Blacksmith"
homepage = "https://github.com/mardiros/pyramid-blacksmith"
name = "pyramid-blacksmith"
readme = "README.rst"
repository = "https://github.com/mardiros/pyramid-blacksmith"
version = "0.3.0"

[tool.poetry.dependencies]
blacksmith = "^0.12.1"
prometheus-client = "^0.12.0"
pyramid = ">1.10, ^2.0"
python = "^3.7"

[tool.poetry.dev-dependencies]
Sphinx = "^4.3.2"
black = "^21.12b0"
coverage = {version = "^6.2", extras = ["toml"]}
flake8 = "^4.0.1"
isort = "^5.10.1"
prometheus-client = "^0.12.0"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
sphinx-rtd-theme = "^1.0.0"
tomlkit = "^0.8.0"
redis = "^4.1.0"
esbonio = "^0.8.0"
mypy = "^0.931"
types-redis = "^4.1.8"
types-setuptools = "^57.4.7"

[tool.poetry.extras]
prometheus = ["prometheus-client"]

[tool.pytest.ini_options]
norecursedirs = "docs"

[tool.pyright]
include = ["src"]
ignore = ["examples"]
typeCheckingMode = "strict"
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportPrivateUsage = false

[tool.isort]
profile = "black"

[tool.coverage.report]
exclude_lines = [
  "if TYPE_CHECKING:",
  "except ImportError:",
  "except pkg_resources.DistributionNotFound:",
]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
