
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-18T16:11:05-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9fa6215bc15b6f1a99c3031a754be2324ad492e9",
 "version": "2.7.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
