
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-18T15:21:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f09df34c4751cb2bb86ba62ee974d4305f2be7ef",
 "version": "2579"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
