
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-21T07:51:57-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d81121297c1052262b02f59f7825638a63874e8b",
 "version": "4.7.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
