[tool.poetry]
name = "tahu"
version = "0.1.0"
description = ""
authors = ["Aitemir Kuandyk <mooniron.k@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
protobuf = "3.19.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
