[build-system]
requires = [
    "setuptools >= 56.0",
    "setuptools_scm >= 2.0.0, <3",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
src = ['src', 'tests']

[tool.pytest.ini_options]
minversion = "6.0"

[tool.mypy]
follow_imports = "normal"
strict_optional = true
files = ['src', 'tests']
