
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-23T12:48:42-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d3a3ef997bc7562d62c3a1ec756f0aee4bb9331",
 "version": "0.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
