[tool.poetry]
name = "legiond"
version = "0.2.4"
description = "A distributed, scalable, and fault-tolerant alerting and monitoring system"
authors = ["Eugene Kovalev <eugene@kovalev.systems>"]
classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
]
documentation="https://gitlab.com/legion-robotnik/legiond/-/wikis/home"
repository="https://gitlab.com/legion-robotnik/legiond"
readme="README.md"
license="GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.3"
robotnikmq = "^0.3.3"
legion-utils = "^0.2.10"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-cov = "^2.11.1"
pylint = "^2.6.0"
mypy = "^0.790"
flake8 = "^3.8.4"

[tool.poetry.scripts]
legiond = 'legiond.cli:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
