
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-20T11:45:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f814aaf06dd39061d8252dbfe6f6ab814375272d",
 "version": "0.8.18b0.dev202201210713"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
