[tool.poetry]
name = "pylayer"
version = "1.0.0"
description = "Make a end-to-end encryption pass. PASSWORD FROM MODULE: ePBfRsT23Le7C4DbM1WoIoo7PUr6VhuFqTOp"
authors = ["OwoNicoo"]
license = "Grub BN - V3"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
