
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-21T14:52:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c031712125a2f7803c7895ca2a2f0955efb4238",
 "version": "2.1.13b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
