
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-20T12:45:15-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e5ee00e6bf1bb5056cd517b37d6923b5eb770bb",
 "version": "1.0.0.post0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
