[tool.poetry]
name = "legion-utils"
version = "0.2.10"
description = "Utilities for Legion Reporters and Monitors"
authors = ["Eugene Kovalev <eugene@kovalev.systems>"]
classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
]
documentation="https://gitlab.com/legion-robotnik/legion-utils"
repository="https://gitlab.com/legion-robotnik/legion-utils"
readme="README.md"
license="GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.8"
robotnikmq = "^0.3.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pylint = "^2.12.2"
mypy = "^0.930"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
