
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-19T16:58:01-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "35d760ceb64ec318f302a6e4d3a4a80feda97a9e",
 "version": "0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
