[tool.poetry]
name = "fritzxhr"
version = "0.1.0"
description = "An interface to FRITZ!Box web settings"
authors = ["Andreas Oberritter <obi@saftware.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.27.1"
defusedxml = "^0.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
