[tool.poetry]
name = "nr.poetry-release"
version = "0.1.2"
description = "A Poetry plugin to automate the release process of Python packages."
authors = ["Niklas Rosenstein <rosensteinniklas@gmail.com>"]
readme = "readme.md"
packages = [{include = "poetry_release", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
"databind.json" = "^1.4.0"
"nr.util" = "^0.4.5"
poetry = "^1.2.0a2"
tomli = "^2.0.0"

[tool.poetry.plugins."poetry.application.plugin"]
release-command = "poetry_release._poetry_plugin:ReleasePlugin"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
