
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-21T09:01:49-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "fcc6e34ea6eadf84bba4d4943ca2fa0614ffb923",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
