# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tikka/slots/pyqt/resources/gui/widgets/account.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountWidget(object):
    def setupUi(self, AccountWidget):
        AccountWidget.setObjectName("AccountWidget")
        AccountWidget.resize(615, 384)
        AccountWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AccountWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SafeImage = QtWidgets.QLabel(AccountWidget)
        self.SafeImage.setMaximumSize(QtCore.QSize(100, 100))
        self.SafeImage.setBaseSize(QtCore.QSize(200, 0))
        self.SafeImage.setText("")
        self.SafeImage.setPixmap(QtGui.QPixmap(":/images/safe_400x400.png"))
        self.SafeImage.setScaledContents(True)
        self.SafeImage.setObjectName("SafeImage")
        self.horizontalLayout.addWidget(self.SafeImage)
        self.BalanceLabel = QtWidgets.QLabel(AccountWidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.BalanceLabel.setFont(font)
        self.BalanceLabel.setObjectName("BalanceLabel")
        self.horizontalLayout.addWidget(self.BalanceLabel, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(6, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LockStatusIcon = QtWidgets.QLabel(AccountWidget)
        self.LockStatusIcon.setMaximumSize(QtCore.QSize(16, 16))
        self.LockStatusIcon.setText("")
        self.LockStatusIcon.setPixmap(QtGui.QPixmap(":/images/locked_cartoon_400x400.png"))
        self.LockStatusIcon.setScaledContents(True)
        self.LockStatusIcon.setObjectName("LockStatusIcon")
        self.horizontalLayout_2.addWidget(self.LockStatusIcon)
        self.PublicKeyLabel = QtWidgets.QLabel(AccountWidget)
        self.PublicKeyLabel.setObjectName("PublicKeyLabel")
        self.horizontalLayout_2.addWidget(self.PublicKeyLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(AccountWidget)
        QtCore.QMetaObject.connectSlotsByName(AccountWidget)

    def retranslateUi(self, AccountWidget):
        #  _translate = QtCore.QCoreApplication.translate
        AccountWidget.setWindowTitle(_("Account"))
        self.BalanceLabel.setText(_("0"))
        self.PublicKeyLabel.setText(_("Public key"))
import tikka.slots.pyqt.resources.icons.index_rc
