# -*- coding: utf-8 -*-
codesTemps = {
    395: "Neige modérée ou forte dans la région avec tonnerre",
    392: "Neige légère parsemée dans la région avec tonnerre",
    389: "Pluie modérée ou forte dans une région avec tonnerre",
    386: "Pluie légère parsemée dans une zone avec tonnerre	",
    377: "Averses modérées ou fortes de granules de glace	",
    374: "Averses légères de grésil	",
    371: "Averses de neige modérées ou fortes",
    368: "Averses de neige légères",
    365: "Averses de grésil modérées ou fortes",
    362: "Averses légères de grésil	",
    359: "Pluie torrentielle	",
    356: "Pluie modérée ou forte",
    353: "Pluie légère	",
    350: "Granules de glace",
    338: "Neige lourde	",
    335: "Neige lourde parsemée",
    332: "Neige modérée		",
    329: "Neige modérée parsemée",
    326: "Neige légère		",
    323: "Neige légère fragmentée",
    320: "Grésil modéré ou fort	",
    317: "Grésil léger		",
    314: "Pluie verglaçante modérée ou forte",
    311: "Pluie verglaçante légère		",
    308: "Forte pluie		",
    305: "Pluie forte par moments",
    302: "Pluie modérée		",
    299: "Pluie modérée par moments	",
    296: "Pluie légère	",
    293: "Pluie légère parsemée",
    284: "Forte bruine verglaçante",
    281: "Bruine verglaçante		",
    266: "Bruine légère		",
    263: "Bruine légère parsemée	",
    260: "Brouillard givrant",
    248: "Brouillard		",
    230: "Blizzard		",
    227: "Poudrerie		",
    200: "Bruine verglaçante à proximité	",
    185: "Bruine verglaçante parsemée à proximité	",
    182: "Grésil parsemé à proximité		",
    179: "Neige parsemée à proximité		",
    176: "Pluie discontinue à proximité	",
    143: "Brouillard		",
    122: "Ciel couvert	",
    119: "Nuageux		",
    116: "Partiellement nuageux",
    113: "Clair/Ensoleill ",
}
