defaults: &defaults
  working_directory: ~/openfisca-france-local
  docker:
    - image: python:3.7

upgrade_pip: &upgrade_pip
  run:
    name: Upgrade pip
    command: pip install --upgrade pip wheel

install_dependencies: &install_dependencies
  run:
    name: Install dependencies
    command: pip install . --upgrade && pip install ".[test,excel-reader]"

check_version: &check_version
  run:
    name: Check version number has been properly updated
    command: |
      git fetch
      .circleci/is-version-number-acceptable.sh


version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *upgrade_pip
      - *install_dependencies
      - run:
          name: Run tests
          command: openfisca test `circleci tests glob "tests/**/*.{yml,yaml}"` --extensions openfisca_france_local
  check_version:
    <<: *defaults
    steps:
      - checkout
      - *check_version


workflows:
  version: 2
  test:
    jobs:
      - test
      - check_version
