[tool.poetry]
name = "kvsh"
version = "0.1.2"
description = "Persistent key-value store for the command line"
authors = ["Aatif Syed <aatifsyedyp@gmail.com>"]
readme = "README.md"
repository = "https://github.com/aatifsyed/kvsh"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
xdg = "^5.1.1"
argcomplete = "^1.12.3"
jsonschema = "^4.2.1"
dataclasses-json = "^0.5.6"
logging-actions = "^0.1.6"
argparse = "^1.4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
black = "^21.11b0"
mypy = "^0.910"

[tool.poetry.scripts]
kv = 'kvsh:kv'
kvv = 'kvsh:kvv'

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "info"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
