
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-24T17:02:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0535335753a553322d16899533b45f027073392b",
 "version": "1.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
