
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-06T14:14:59-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3544d9eb94f56ae2635a0fa73e12ed67bd38a242",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
