[package]
name = "parallelsort_rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "parallelsort_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }
crossbeam = "0.8"
rand = "0.8.0"
time = "0.3.5"
thread = "0.1.0"
