[tool.poetry]
name = "kapla-services"
version = "0.1.0"
description = ""
authors = ["charbonnierg <guillaume.charbonnier@araymond.com>"]
packages = [{ include = "kapla", from = "src" }]

[tool.poetry.dependencies]
python = "^3.8"
nats-py = "^2.0.0-rc.5"
pydantic = "^1.8.2"
anyio = "^3.4.0"
Brotli = "^1.0.9"

[tool.poetry.dev-dependencies]
pytest-cov = "^3.0.0"
pytest = "^6.2.5"
mypy = "^0.910"
black = "^21.12b0"
flake8 = "^4.0.1"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
