# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/uifiles/phptwdgt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_phptwdgt(object):
    def setupUi(self, phptwdgt):
        phptwdgt.setObjectName("phptwdgt")
        phptwdgt.resize(420, 110)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(phptwdgt.sizePolicy().hasHeightForWidth())
        phptwdgt.setSizePolicy(sizePolicy)
        phptwdgt.setMinimumSize(QtCore.QSize(420, 110))
        phptwdgt.setMaximumSize(QtCore.QSize(420, 110))
        self.phptdvce = QtWidgets.QLabel(phptwdgt)
        self.phptdvce.setGeometry(QtCore.QRect(55, 5, 360, 20))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phptdvce.sizePolicy().hasHeightForWidth())
        self.phptdvce.setSizePolicy(sizePolicy)
        self.phptdvce.setMinimumSize(QtCore.QSize(360, 20))
        self.phptdvce.setMaximumSize(QtCore.QSize(360, 20))
        self.phptdvce.setStyleSheet('font: 13pt "Barlow";')
        self.phptdvce.setObjectName("phptdvce")
        self.phptfsys = QtWidgets.QLabel(phptwdgt)
        self.phptfsys.setGeometry(QtCore.QRect(55, 70, 360, 15))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phptfsys.sizePolicy().hasHeightForWidth())
        self.phptfsys.setSizePolicy(sizePolicy)
        self.phptfsys.setMinimumSize(QtCore.QSize(360, 15))
        self.phptfsys.setMaximumSize(QtCore.QSize(360, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.phptfsys.setFont(font)
        self.phptfsys.setStyleSheet('font: 10pt "Inter";')
        self.phptfsys.setObjectName("phptfsys")
        self.phptnumb = QtWidgets.QLabel(phptwdgt)
        self.phptnumb.setGeometry(QtCore.QRect(5, 5, 40, 20))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phptnumb.sizePolicy().hasHeightForWidth())
        self.phptnumb.setSizePolicy(sizePolicy)
        self.phptnumb.setMinimumSize(QtCore.QSize(40, 20))
        self.phptnumb.setMaximumSize(QtCore.QSize(40, 20))
        self.phptnumb.setStyleSheet('font: 13pt "Barlow";')
        self.phptnumb.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.phptnumb.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.phptnumb.setObjectName("phptnumb")
        self.phptlabl = QtWidgets.QLabel(phptwdgt)
        self.phptlabl.setGeometry(QtCore.QRect(5, 30, 40, 15))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phptlabl.sizePolicy().hasHeightForWidth())
        self.phptlabl.setSizePolicy(sizePolicy)
        self.phptlabl.setMinimumSize(QtCore.QSize(40, 15))
        self.phptlabl.setMaximumSize(QtCore.QSize(40, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.phptlabl.setFont(font)
        self.phptlabl.setStyleSheet('font: 10pt "Inter";')
        self.phptlabl.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.phptlabl.setObjectName("phptlabl")
        self.phptfutl = QtWidgets.QLabel(phptwdgt)
        self.phptfutl.setGeometry(QtCore.QRect(55, 30, 360, 15))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phptfutl.sizePolicy().hasHeightForWidth())
        self.phptfutl.setSizePolicy(sizePolicy)
        self.phptfutl.setMinimumSize(QtCore.QSize(360, 15))
        self.phptfutl.setMaximumSize(QtCore.QSize(360, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.phptfutl.setFont(font)
        self.phptfutl.setStyleSheet('font: 10pt "Inter";')
        self.phptfutl.setObjectName("phptfutl")
        self.phptmxfp = QtWidgets.QLabel(phptwdgt)
        self.phptmxfp.setGeometry(QtCore.QRect(55, 90, 360, 15))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phptmxfp.sizePolicy().hasHeightForWidth())
        self.phptmxfp.setSizePolicy(sizePolicy)
        self.phptmxfp.setMinimumSize(QtCore.QSize(360, 15))
        self.phptmxfp.setMaximumSize(QtCore.QSize(360, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.phptmxfp.setFont(font)
        self.phptmxfp.setStyleSheet('font: 10pt "Inter";')
        self.phptmxfp.setObjectName("phptmxfp")
        self.phptpgbr = QtWidgets.QProgressBar(phptwdgt)
        self.phptpgbr.setGeometry(QtCore.QRect(55, 50, 360, 15))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phptpgbr.sizePolicy().hasHeightForWidth())
        self.phptpgbr.setSizePolicy(sizePolicy)
        self.phptpgbr.setMinimumSize(QtCore.QSize(360, 15))
        self.phptpgbr.setMaximumSize(QtCore.QSize(360, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        self.phptpgbr.setFont(font)
        self.phptpgbr.setStyleSheet(
            'border: 1px solid #808080; border-radius: 0px; font: 8pt "Inter";'
        )
        self.phptpgbr.setProperty("value", 0)
        self.phptpgbr.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.phptpgbr.setTextVisible(True)
        self.phptpgbr.setInvertedAppearance(False)
        self.phptpgbr.setObjectName("phptpgbr")
        self.phptline = QtWidgets.QFrame(phptwdgt)
        self.phptline.setGeometry(QtCore.QRect(50, 5, 1, 100))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phptline.sizePolicy().hasHeightForWidth())
        self.phptline.setSizePolicy(sizePolicy)
        self.phptline.setMinimumSize(QtCore.QSize(1, 100))
        self.phptline.setMaximumSize(QtCore.QSize(1, 100))
        self.phptline.setStyleSheet("border: 1px solid #808080;")
        self.phptline.setFrameShape(QtWidgets.QFrame.VLine)
        self.phptline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.phptline.setObjectName("phptline")

        self.retranslateUi(phptwdgt)
        QtCore.QMetaObject.connectSlotsByName(phptwdgt)

    def retranslateUi(self, phptwdgt):
        _translate = QtCore.QCoreApplication.translate
        phptwdgt.setWindowTitle(_translate("phptwdgt", "Form"))
        self.phptdvce.setText(_translate("phptwdgt", "DEVICE"))
        self.phptfsys.setText(_translate("phptwdgt", "MOUNTPOINT (FILESYSTEM)"))
        self.phptnumb.setText(_translate("phptwdgt", "0"))
        self.phptlabl.setText(_translate("phptwdgt", "#PART"))
        self.phptfutl.setText(
            _translate(
                "phptwdgt",
                '<html><head/><body><p><span style=" font-weight:700;">FREE: </span>000.00XB, <span style=" font-weight:700;">USED: </span>000.00XB, <span style=" font-weight:700;">TOTAL: </span>000.00XB</p></body></html>',
            )
        )
        self.phptmxfp.setText(
            _translate(
                "phptwdgt",
                '<html><head/><body><p><span style=" font-weight:700;">Max filename length: </span>XXXX, <span style=" font-weight:700;">Max pathname length: </span>XXXX</p></body></html>',
            )
        )
        self.phptpgbr.setFormat(_translate("phptwdgt", "%p% "))
