
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-18T13:08:43-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "07c304de840fdea80e9dc906f4c0b7dd97af71f4",
 "version": "4.9.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
