[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sborl"
dynamic = ["version", "description"]
dependencies = [
    "jsonschema",
    "ops",
    "pyyaml",
]

[options]
packages = "find:"
