[package]
name = "ms_toollib"
version = "1.2.9"
description = "Algorithms  for Minesweeper"
documentation = "https://docs.rs/ms_toollib/"
license = "MIT"
readme = "README.md"
keywords = ["minesweeper", "possibility", "mine", "laymine"]
edition = "2018"
authors = ["Wang Jianing <wangjianing@88.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { version ="0.15.1", features = ["extension-module"] }
ms_toollib = { version ="1.2.10", features = ["py"] }


[lib]
name = "ms_toollib"
crate-type = ["cdylib", "lib"]








