
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-24T19:25:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2c49450bdf05bccb2b086463ccc4c1fab0482d3",
 "version": "0.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
