
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-17T19:57:04-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "960d7b4e9f20a69f88e92488117eeb5b8c653779",
 "version": "4.9.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
