[tool.poetry]
name = "functionwords"
version = "0.8"
description = "Extract curated Chinese and English function words from texts."
authors = ["Haining Wang <hw56@indiana.edu>"]
readme = "README.md"
license = "CC-BY-SA 4.0"
repository = "https://github.com/Wang-Haining/functionwords"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.13"]
build-backend = "poetry.masonry.api"
