[tool.poetry]
authors = ["niwla23 <alwin@cloudserver.click>"]
description = "This Scrapper can get data from iserv servers hosting Untis plans. (Common in germany)"
license = "MIT"
name = "iservscrapping"
version = "5.0.1"

packages = [
  {include = "iservscrapping"},
]

[tool.poetry.dependencies]
Markdown = "^3.3.6"
beautifulsoup4 = "^4.10.0"
lxml = "^4.7.1"
pendulum = "^2.1.2"
python = "^3.10"
requests = "^2.27.1"
requests-cache = "^0.9.1"

[tool.poetry.dev-dependencies]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
