
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-21T16:42:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "bafde78cdf45e9ea440804bd48ff9137bb4a0d12",
 "version": "v2.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
