[tool.poetry]
name = "Mikrotik_HTML_Documentation"
version = "0.1.3c"
description = "Mikrotik Config to Markup"
authors = ["Angelo Poggi <angelo.poggi@opti9tech.com>"]
homepage = "https://github.com/purplecomputer/Mikrotik_HTML_Documentation"
repository = "https://github.com/purplecomputer/Mikrotik_HTML_Documentation"
keywords = ["mikrotik", "mikrotik-documentation"]
license = "Apache-2.0"
readme = "README.md"
include = [
    "LICENSE",
    "README.md",
    ]
packages = [
    { include = "mt_html" },
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.3"
RouterOS-api = "0.17.0"
json2html = "^1.3.0"
python-dotenv = "^0.19.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mt-html = 'mt_html.cli:cli'