
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-17T13:32:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "353b32aeb3897c7ffb50c9a5759091928f493f1d",
 "version": "3.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
