[tool.poetry]
name = "raclients"
version = "0.11.4"
description = "Clients for OS2mo/LoRa"
authors = ["Magenta <info@magenta.dk>"]
license = "MPL-2.0"
readme = "README.md"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/ra-clients"
keywords = ["os2mo", "lora"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.4"
more-itertools = "^8.7.0"
tqdm = "^4.60.0"
pydantic = "^1.9.0"
jsonschema = "^3.2.0"
fastapi = "^0.72.0"
ramodels = "^5.0.0"
ra-utils = {extras = ["headers"], version = "^0.4.0"}
httpx = "^0.21.3"
Authlib = "^0.15.5"
gql = {allow-prereleases = true, version = "3.0.0rc1"}
structlog = "^21.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.5b0"
flake8 = "^3.9.1"
mypy = "^0.812"
reorder-python-imports = "^2.5.0"
pre-commit = "^2.12.1"
pytest-aioresponses = "^0.1.0"
pytest-cov = "^2.12.1"
respx = "^0.19.0"

[tool.autopub]
git-username = "MagentaBot"
git-email = "info@magenta.dk"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
