# To create the dev environment use
# conda env create --prefix=./env -f requirements/environment.yml
#
# To remove env
# conda env remove -p ./env

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.6
  - pip
  - pip:
    - -r requirements_dev.txt
    #- -e ./..