[tool.poetry]
name = "BaiduPCS-Py"
homepage = "https://github.com/PeterDing/BaiduPCS-Py"
version = "0.6.32"
description = "Baidu Pcs Api and App"
authors = ["PeterDing <dfhayst@gmail.com>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
build = "build.py"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.27.1"
rich = "^11.0.0"
requests-toolbelt = "^0.9.1"
Pillow = "^9.0.0"
click = "^8.0.3"
typing-extensions = "^4.0.1"
aget = "^0.1.17"
chardet = "^4.0.0"
fastapi = "^0.71.0"
uvicorn = "^0.16.0"
Jinja2 = "^3.0.3"
cryptography = "^36.0.1"
filelock = "^3.4.2"
Cython = "^0.29.26"
passlib = "^1.7.4"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
mypy = "^0.931"
black = "^21.12b0"
setuptools = "^60.5.0"
Cython = "^0.29.26"

[tool.poetry.scripts]
BaiduPCS-Py = 'baidupcs_py.app:main'

[build-system]
requires = ["poetry-core>=1.0.0", "cython", "wheel", "setuptools"]
build-backend = "poetry.core.masonry.api"
