# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tikka/slots/pyqt/resources/gui/windows/account_unlock.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UnlockDialog(object):
    def setupUi(self, UnlockDialog):
        UnlockDialog.setObjectName("UnlockDialog")
        UnlockDialog.resize(902, 400)
        UnlockDialog.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(UnlockDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(UnlockDialog)
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/unlocked_cartoon_400x400.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(UnlockDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.public_key_value_label = QtWidgets.QLabel(UnlockDialog)
        self.public_key_value_label.setText("")
        self.public_key_value_label.setObjectName("public_key_value_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.public_key_value_label)
        self.access_code_line_edit = QtWidgets.QLineEdit(UnlockDialog)
        self.access_code_line_edit.setText("")
        self.access_code_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.access_code_line_edit.setObjectName("access_code_line_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.access_code_line_edit)
        self.label_3 = QtWidgets.QLabel(UnlockDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(UnlockDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cesium_password_line_edit = QtWidgets.QLineEdit(UnlockDialog)
        self.cesium_password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.cesium_password_line_edit.setObjectName("cesium_password_line_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cesium_password_line_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.showButton = QtWidgets.QPushButton(UnlockDialog)
        self.showButton.setObjectName("showButton")
        self.verticalLayout.addWidget(self.showButton, 0, QtCore.Qt.AlignHCenter)
        self.error_label = QtWidgets.QLabel(UnlockDialog)
        self.error_label.setStyleSheet("color : rgb(255, 0, 0)")
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label, 0, QtCore.Qt.AlignHCenter)
        self.buttonBox = QtWidgets.QDialogButtonBox(UnlockDialog)
        self.buttonBox.setEnabled(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(UnlockDialog)
        self.buttonBox.accepted.connect(UnlockDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(UnlockDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UnlockDialog)

    def retranslateUi(self, UnlockDialog):
        #  _translate = QtCore.QCoreApplication.translate
        UnlockDialog.setWindowTitle(_("Unlock account"))
        self.label_2.setText(_("Public key"))
        self.label_3.setText(_("Access code"))
        self.label_4.setText(_("Cesium password"))
        self.showButton.setText(_("Show"))
import tikka.slots.pyqt.resources.icons.index_rc
