
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-17T17:53:26-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "72983d5313371c36031e579368d4ea25648c38af",
 "version": "2022.1.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
