
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-19T16:29:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e67c4abb28c645610bbcefe568e6b3745e06231b",
 "version": "1.19.10.post0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
