# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: programl/proto/program_graph.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from programl.third_party.tensorflow import features_pb2 as programl_dot_third__party_dot_tensorflow_dot_features__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='programl/proto/program_graph.proto',
  package='programl',
  syntax='proto3',
  serialized_options=b'\n\014com.programlB\021ProgramGraphProtoP\001Z\nprogramlpb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"programl/proto/program_graph.proto\x12\x08programl\x1a.programl/third_party/tensorflow/features.proto\"\xb8\x01\n\x0cProgramGraph\x12\x1c\n\x04node\x18\x01 \x03(\x0b\x32\x0e.programl.Node\x12\x1c\n\x04\x65\x64ge\x18\x02 \x03(\x0b\x32\x0e.programl.Edge\x12$\n\x08\x66unction\x18\x04 \x03(\x0b\x32\x12.programl.Function\x12 \n\x06module\x18\x05 \x03(\x0b\x32\x10.programl.Module\x12$\n\x08\x66\x65\x61tures\x18\x06 \x01(\x0b\x32\x12.programl.Features\"\xb3\x01\n\x04Node\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.programl.Node.Type\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08\x66unction\x18\x04 \x01(\x05\x12\r\n\x05\x62lock\x18\x07 \x01(\x05\x12$\n\x08\x66\x65\x61tures\x18\x08 \x01(\x0b\x32\x12.programl.Features\"3\n\x04Type\x12\x0f\n\x0bINSTRUCTION\x10\x00\x12\x0c\n\x08VARIABLE\x10\x01\x12\x0c\n\x08\x43ONSTANT\x10\x02\"\xaa\x01\n\x04\x45\x64ge\x12!\n\x04\x66low\x18\x01 \x01(\x0e\x32\x13.programl.Edge.Flow\x12\x10\n\x08position\x18\x02 \x01(\x05\x12\x0e\n\x06source\x18\x03 \x01(\x05\x12\x0e\n\x06target\x18\x04 \x01(\x05\x12$\n\x08\x66\x65\x61tures\x18\x05 \x01(\x0b\x32\x12.programl.Features\"\'\n\x04\x46low\x12\x0b\n\x07\x43ONTROL\x10\x00\x12\x08\n\x04\x44\x41TA\x10\x01\x12\x08\n\x04\x43\x41LL\x10\x02\"N\n\x08\x46unction\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06module\x18\x02 \x01(\x05\x12$\n\x08\x66\x65\x61tures\x18\x03 \x01(\x0b\x32\x12.programl.Features\"<\n\x06Module\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x08\x66\x65\x61tures\x18\x02 \x01(\x0b\x32\x12.programl.FeaturesB/\n\x0c\x63om.programlB\x11ProgramGraphProtoP\x01Z\nprogramlpbb\x06proto3'
  ,
  dependencies=[programl_dot_third__party_dot_tensorflow_dot_features__pb2.DESCRIPTOR,])



_NODE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='programl.Node.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INSTRUCTION', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VARIABLE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONSTANT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=412,
  serialized_end=463,
)
_sym_db.RegisterEnumDescriptor(_NODE_TYPE)

_EDGE_FLOW = _descriptor.EnumDescriptor(
  name='Flow',
  full_name='programl.Edge.Flow',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONTROL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DATA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CALL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=597,
  serialized_end=636,
)
_sym_db.RegisterEnumDescriptor(_EDGE_FLOW)


_PROGRAMGRAPH = _descriptor.Descriptor(
  name='ProgramGraph',
  full_name='programl.ProgramGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='programl.ProgramGraph.node', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edge', full_name='programl.ProgramGraph.edge', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='function', full_name='programl.ProgramGraph.function', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='module', full_name='programl.ProgramGraph.module', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='features', full_name='programl.ProgramGraph.features', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=281,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='programl.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='programl.Node.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='programl.Node.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='function', full_name='programl.Node.function', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block', full_name='programl.Node.block', index=3,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='features', full_name='programl.Node.features', index=4,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NODE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=463,
)


_EDGE = _descriptor.Descriptor(
  name='Edge',
  full_name='programl.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='flow', full_name='programl.Edge.flow', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='programl.Edge.position', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='programl.Edge.source', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target', full_name='programl.Edge.target', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='features', full_name='programl.Edge.features', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EDGE_FLOW,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=466,
  serialized_end=636,
)


_FUNCTION = _descriptor.Descriptor(
  name='Function',
  full_name='programl.Function',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='programl.Function.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='module', full_name='programl.Function.module', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='features', full_name='programl.Function.features', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=638,
  serialized_end=716,
)


_MODULE = _descriptor.Descriptor(
  name='Module',
  full_name='programl.Module',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='programl.Module.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='features', full_name='programl.Module.features', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=718,
  serialized_end=778,
)

_PROGRAMGRAPH.fields_by_name['node'].message_type = _NODE
_PROGRAMGRAPH.fields_by_name['edge'].message_type = _EDGE
_PROGRAMGRAPH.fields_by_name['function'].message_type = _FUNCTION
_PROGRAMGRAPH.fields_by_name['module'].message_type = _MODULE
_PROGRAMGRAPH.fields_by_name['features'].message_type = programl_dot_third__party_dot_tensorflow_dot_features__pb2._FEATURES
_NODE.fields_by_name['type'].enum_type = _NODE_TYPE
_NODE.fields_by_name['features'].message_type = programl_dot_third__party_dot_tensorflow_dot_features__pb2._FEATURES
_NODE_TYPE.containing_type = _NODE
_EDGE.fields_by_name['flow'].enum_type = _EDGE_FLOW
_EDGE.fields_by_name['features'].message_type = programl_dot_third__party_dot_tensorflow_dot_features__pb2._FEATURES
_EDGE_FLOW.containing_type = _EDGE
_FUNCTION.fields_by_name['features'].message_type = programl_dot_third__party_dot_tensorflow_dot_features__pb2._FEATURES
_MODULE.fields_by_name['features'].message_type = programl_dot_third__party_dot_tensorflow_dot_features__pb2._FEATURES
DESCRIPTOR.message_types_by_name['ProgramGraph'] = _PROGRAMGRAPH
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Edge'] = _EDGE
DESCRIPTOR.message_types_by_name['Function'] = _FUNCTION
DESCRIPTOR.message_types_by_name['Module'] = _MODULE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProgramGraph = _reflection.GeneratedProtocolMessageType('ProgramGraph', (_message.Message,), {
  'DESCRIPTOR' : _PROGRAMGRAPH,
  '__module__' : 'programl.proto.program_graph_pb2'
  # @@protoc_insertion_point(class_scope:programl.ProgramGraph)
  })
_sym_db.RegisterMessage(ProgramGraph)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'programl.proto.program_graph_pb2'
  # @@protoc_insertion_point(class_scope:programl.Node)
  })
_sym_db.RegisterMessage(Node)

Edge = _reflection.GeneratedProtocolMessageType('Edge', (_message.Message,), {
  'DESCRIPTOR' : _EDGE,
  '__module__' : 'programl.proto.program_graph_pb2'
  # @@protoc_insertion_point(class_scope:programl.Edge)
  })
_sym_db.RegisterMessage(Edge)

Function = _reflection.GeneratedProtocolMessageType('Function', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTION,
  '__module__' : 'programl.proto.program_graph_pb2'
  # @@protoc_insertion_point(class_scope:programl.Function)
  })
_sym_db.RegisterMessage(Function)

Module = _reflection.GeneratedProtocolMessageType('Module', (_message.Message,), {
  'DESCRIPTOR' : _MODULE,
  '__module__' : 'programl.proto.program_graph_pb2'
  # @@protoc_insertion_point(class_scope:programl.Module)
  })
_sym_db.RegisterMessage(Module)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
