[tool.poetry]
name = "li_api"
version = "0.1.0"
description = ""
authors = ["lex <lex@legatoivy.tech>"]

[tool.poetry.dependencies]
python = "^3.8"
grpcio = "1.29.0"
grpcio-tools = "1.29.0"
protobuf = "3.12.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
