[tool.poetry]
name = "nonebot-plugin-datastore"
version = "0.1.0"
description = "适用于 Nonebot2 的数据存储插件"
authors = ["hemengyang <hmy0119@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/he0119/nonebot-plugin-datastore"
repository = "https://github.com/he0119/nonebot-plugin-datastore"
documentation = "https://github.com/he0119/nonebot-plugin-datastore#readme"

[tool.poetry.dependencies]
python = "^3.7.3"
nonebot2 = {extras = ["httpx"], version = "^2.0.0-beta.1"}
nonebot-plugin-localstore = "^0.1.0"
sqlmodel = "^0.0.6"
aiosqlite = "^0.17.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
isort = "^5.10.1"

[[tool.poetry.source]]
default = true
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88
skip_gitignore = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
