
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-21T09:48:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "db94c69523e9cc69b1218c4b311ab139edde97cf",
 "version": "0.5.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
