
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-20T11:54:56-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "a73ac95c22f79fde7ab1453ff1eb9d30254dfad8",
 "version": "2.3.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
