from http import HTTPStatus

# locals().update(HTTPStatus.__members__)
# for e in sorted(HTTPStatus): print(f'HTTP_{e.value}_{e.name} = HTTPStatus.{e.name}')

HTTP_200_OK = HTTPStatus.OK
HTTP_400_BAD_REQUEST = HTTPStatus.BAD_REQUEST
HTTP_401_UNAUTHORIZED = HTTPStatus.UNAUTHORIZED
HTTP_403_FORBIDDEN = HTTPStatus.FORBIDDEN
HTTP_404_NOT_FOUND = HTTPStatus.NOT_FOUND
HTTP_405_METHOD_NOT_ALLOWED = HTTPStatus.METHOD_NOT_ALLOWED
HTTP_415_UNSUPPORTED_MEDIA_TYPE = HTTPStatus.UNSUPPORTED_MEDIA_TYPE
HTTP_422_UNPROCESSABLE_ENTITY = HTTPStatus.UNPROCESSABLE_ENTITY
HTTP_500_INTERNAL_SERVER_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR
