#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['binance_pandas_dataframe']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

entry_points = \
{'console_scripts': ['download_aggTrade = '
                     'binance_pandas_dataframe.download_aggTrade:main',
                     'download_kline = '
                     'binance_pandas_dataframe.download_kline:main',
                     'download_trade = '
                     'binance_pandas_dataframe.download_trade:main']}

setup(name='binance_pandas_dataframe',
      version='0.2',
      description='binance_pandas_dataframe.    ',
      author='binance',
      author_email=None,
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      entry_points=entry_points,
     )
