[build-system]
requires = [
    "pandas_datareader==0.10.0",
    "pandas==1.3.3",
    "matplotlib==3.4.3",
    "mplcursors==0.5.1",
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"