
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-17T20:41:12+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "61d69ab5b649f9a9eac454e163027d2321b3704b",
 "version": "2.0.4-1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
