
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-20T09:48:03-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "f3e45a9f6dafb5f337fa8875d16c26e7a43213b1",
 "version": "2.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
