[tool.poetry]
name = "xarray-multiscale"
version = "0.3.1"
description = ""
authors = ["Davis Vann Bennett <davis.v.bennett@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<4"
xarray = ">=0.17"
mypy = "^0.790"
scipy = "^1.5.4"
numpy = "^1.19.4"
dask = "^2021.9.1"
Jinja2 = "^3.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[mypy]
plugins = "numpy.typing.mypy_plugin"