[tool.poetry]
name = "fastack-mail"
version = "0.1.0"
description = "Simple plugin for sending email"
authors = ["aprilahijriyan <hijriyan23@gmail.com>"]
license = "MIT"
maintainers = ["aprilahijriyan <37798612+aprilahijriyan@users.noreply.github.com>"]
readme = "README.md"
homepage = "https://github.com/fastack-dev/fastack-mail"
repository = "https://github.com/fastack-dev/fastack-mail"
classifiers = [
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Topic :: Internet",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
fastack = "^4.0.0"
aiosmtplib = "^1.1.6"
pydantic = {extras = ["email"], version = "^1.9.0"}

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"
ipython = "^7.31.1"

[tool.poetry.urls]

"Bug Tracker" = "https://github.com/fastack-dev/fastack-mail/issues"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
