[tool.poetry]
name = "cherryadmin"
version = "5.21"
description = "CherryPy admin framework"
keywords = ["admin", "framework", "web"]
repository = "https://github.com/martastain/cherryadmin"
authors = ["Martin Wacker <martas@imm.cz>"]
license = "MIT"
readme = "README.md"
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
]

[tool.poetry.dependencies]
python = "^3.6"
nxtools = "^1.6"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
test = 'scripts:test'
docs = 'scripts:docs'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
