
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-18T11:08:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f75e14fbcaac1673875eec3ceef8f68219ed4da",
 "version": "0.8.18b0.dev202201190710"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
