
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-22T22:42:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "80c64ea7b7d66148cbb65cfa9b342e599a431897",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
