[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 96
target-version = ['py310']

[tool.poetry]
name = "fondat-core"
version = "3.0.18"
description = "A foundation for asynchronous Python resource-oriented applications."
readme = "README.md"
authors = ["fondat-core authors"]
homepage = "https://github.com/fondat/fondat/"
documentation = "https://github.com/fondat/fondat/tree/main/docs"
license = "MIT"
keywords = ["asgi", "framework", "resource", "openapi"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]
packages = [
    { include = "fondat" }
]

[tool.poetry.dependencies]
python = "^3.9"
aiosqlite = "^0.16"
iso8601 = "^0.1"
multidict = "^5.2"
wrapt = "^1.13"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pre-commit = "^2.17"
pytest = "^6.2"
pytest-asyncio = "^0.14"
pytest-cov = "^2.12"
