name: nr.util
version: 0.4.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
description: General purpose Python utility library.
requirements:
 - python ^3.10
extra-requirements:
  config:
    - databind.core ^1.3.2
typed: true
test-drivers:
- type: pytest
- type: mypy
