[tool.poetry]
name = "disfs"
version = "0.1.0"
description = "Discord-based filesystem"
authors = ["witherornot"]

[tool.poetry.dependencies]
python = "^3.7"
keyring = "^23.5.0"
requests = "^2.27.1"
requests-toolbelt = "^0.9.1"
config-path = "^1.0.2"
pycryptodome = "^3.12.0"
tqdm = "^4.62.3"

[tool.poetry.scripts]
disfs = 'disfs.cli:main'

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
