
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-21T12:53:03-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9e04011862236c4f0d9b85ab8346758a8286b1d",
 "version": "3.0.0a8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
