[tool.poetry]
name = "jcutil"
version = "1.0.4"
description = "Some python util tolls in one package for your web app'"
authors = ["Jochen.He <thjl@hotmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
jcramda = "^1.0.6"
colorama = "^0.4.4"
click = "^8.0.3"
PyYAML = "^6.0"
python-consul = "^1.1.0"
pycryptodomex = "^3.11.0"
pymongo = "^4.0"
python-dotenv = "^0.19.2"
joblib = {version = "^1.1.0", optional = true}
python-redis = {version = "^0.3.0", optional = true}
SQLAlchemy = {version = "^1.4.27", optional = true}
aiohttp = "^3.8.1"
redis-py-cluster = "^2.1.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pylint = "^2.12.1"
flake8 = "^4.0.1"
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0", "wheel"]
build-backend = "poetry.core.masonry.api"
