
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-18T07:50:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "087e87cfc3c485cafe76a03df767311590288e34",
 "version": "0.0.10rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
