
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-24T18:10:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f16e0ffa4f3cf55c867104c376e9c4502164607",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
