[tool.poetry]
name = "rubiales_nlp"
version = "0.1.0"
description = "Solve NLP common tasks"
authors = ["Alberto Rubiales <al.rubiales.b@gmail.com>"]
readme = "README.md"
homepage = ""
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8, <=3.10"
flake8 = "^4.0.1"
nltk = "^3.6.7"
black = "^21.12b0"
spacy = "^3.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
