[tool.poetry]
name = "poetry-scaffold-plugin"
version = "0.1.0"
description = "Poetry plugin that installs and configures dev dependencies, so you don't have to."
authors = ["Ellen Potter <38250543+ellen364@users.noreply.github.com>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "poetry_scaffold_plugin" }]

[tool.poetry.plugins."poetry.application.plugin"]
scaffold = "poetry_scaffold_plugin.plugins:ScaffoldPlugin"

[tool.poetry.dependencies]
python = "^3.8"
poetry = "^1.2.0a2"
cleo = "^1.0.0a4"
tomlkit = "^0.8.0"

[tool.poetry.group.dev.dependencies]
pytest = "^6.2.5"
coverage = { extras = ["toml"], version = "^6.2" }
pytest-cov = "^3.0.0"
pytest-mock = "^3.6.1"
hypothesis = "^6.35.1"
hypothesis-fspaths = "^0.1"
black = "^21.12-beta.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
flake8-bugbear = "^22.1.11"
mypy = "^0.931"
semgrep = "^0.78.0"
pre-commit = "^2.16.0"
pdbpp = "^0.10.3"
ipython = "^8.0.0"

[tool.isort]
profile = "black"

[tool.coverage.run]
source = ["poetry_scaffold_plugin"]
omit = ["tests/*"]
branch = true

[tool.coverage.report]
show_missing = true
sort = "-Cover"

[tool.mypy]
[[tool.mypy.overrides]]
module = ["cleo.*", "hypothesis_fspaths.*", "poetry.*"]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
