
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-18T10:05:13-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6d15536c768d28a97b5cfcce5fac4189ccf61c7",
 "version": "4.9.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
