# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pii-analysis-requests/pii-analysis-request.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pii-analysis-requests/pii-analysis-request.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n0pii-analysis-requests/pii-analysis-request.proto\"\xeb\x01\n\x12PIIAnalysisRequest\x12\x14\n\x0c\x65ntity_types\x18\x01 \x03(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x17\n\x0fscore_threshold\x18\x03 \x01(\x01\x12\x30\n\x0ctext_payload\x18\x04 \x01(\x0b\x32\x18.PIIAnalysisRequest.TextH\x00\x1a\x32\n\x04Text\x12*\n\x06source\x18\x01 \x01(\x0b\x32\x1a.PIIAnalysisRequest.Source\x1a\"\n\x06Source\x12\r\n\x03URL\x18\x01 \x01(\tH\x00\x42\t\n\x07sourcesB\n\n\x08payloadsb\x06proto3'
)




_PIIANALYSISREQUEST_TEXT = _descriptor.Descriptor(
  name='Text',
  full_name='PIIAnalysisRequest.Text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='PIIAnalysisRequest.Text.source', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=240,
)

_PIIANALYSISREQUEST_SOURCE = _descriptor.Descriptor(
  name='Source',
  full_name='PIIAnalysisRequest.Source',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='URL', full_name='PIIAnalysisRequest.Source.URL', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sources', full_name='PIIAnalysisRequest.Source.sources',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=242,
  serialized_end=276,
)

_PIIANALYSISREQUEST = _descriptor.Descriptor(
  name='PIIAnalysisRequest',
  full_name='PIIAnalysisRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_types', full_name='PIIAnalysisRequest.entity_types', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='PIIAnalysisRequest.language', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score_threshold', full_name='PIIAnalysisRequest.score_threshold', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_payload', full_name='PIIAnalysisRequest.text_payload', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PIIANALYSISREQUEST_TEXT, _PIIANALYSISREQUEST_SOURCE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payloads', full_name='PIIAnalysisRequest.payloads',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=53,
  serialized_end=288,
)

_PIIANALYSISREQUEST_TEXT.fields_by_name['source'].message_type = _PIIANALYSISREQUEST_SOURCE
_PIIANALYSISREQUEST_TEXT.containing_type = _PIIANALYSISREQUEST
_PIIANALYSISREQUEST_SOURCE.containing_type = _PIIANALYSISREQUEST
_PIIANALYSISREQUEST_SOURCE.oneofs_by_name['sources'].fields.append(
  _PIIANALYSISREQUEST_SOURCE.fields_by_name['URL'])
_PIIANALYSISREQUEST_SOURCE.fields_by_name['URL'].containing_oneof = _PIIANALYSISREQUEST_SOURCE.oneofs_by_name['sources']
_PIIANALYSISREQUEST.fields_by_name['text_payload'].message_type = _PIIANALYSISREQUEST_TEXT
_PIIANALYSISREQUEST.oneofs_by_name['payloads'].fields.append(
  _PIIANALYSISREQUEST.fields_by_name['text_payload'])
_PIIANALYSISREQUEST.fields_by_name['text_payload'].containing_oneof = _PIIANALYSISREQUEST.oneofs_by_name['payloads']
DESCRIPTOR.message_types_by_name['PIIAnalysisRequest'] = _PIIANALYSISREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PIIAnalysisRequest = _reflection.GeneratedProtocolMessageType('PIIAnalysisRequest', (_message.Message,), {

  'Text' : _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), {
    'DESCRIPTOR' : _PIIANALYSISREQUEST_TEXT,
    '__module__' : 'pii_analysis_requests.pii_analysis_request_pb2'
    # @@protoc_insertion_point(class_scope:PIIAnalysisRequest.Text)
    })
  ,

  'Source' : _reflection.GeneratedProtocolMessageType('Source', (_message.Message,), {
    'DESCRIPTOR' : _PIIANALYSISREQUEST_SOURCE,
    '__module__' : 'pii_analysis_requests.pii_analysis_request_pb2'
    # @@protoc_insertion_point(class_scope:PIIAnalysisRequest.Source)
    })
  ,
  'DESCRIPTOR' : _PIIANALYSISREQUEST,
  '__module__' : 'pii_analysis_requests.pii_analysis_request_pb2'
  # @@protoc_insertion_point(class_scope:PIIAnalysisRequest)
  })
_sym_db.RegisterMessage(PIIAnalysisRequest)
_sym_db.RegisterMessage(PIIAnalysisRequest.Text)
_sym_db.RegisterMessage(PIIAnalysisRequest.Source)


# @@protoc_insertion_point(module_scope)
