
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-18T15:17:20-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "306a10025557b657a3c1033f8ae1ed4a5c00c7bb",
 "version": "1.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
