
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-17T14:14:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6ab819ea93b9e54f38158061c390ecff512591e",
 "version": "1.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
