[tool.poetry]
name = "c27cache"
version = "0.1.6"
description = "A simple caching library."
license = "Apache-2.0"
authors = ["ragequilt <sid.ravichandran@gmail.com>"]
packages = [{include="c27cache"}]
include = ["REAMDE.md", "LICENSE"]
readme = "README.md"
repository = "https://gitlab.com/core-27/c27cache.git"
documentation = "https://gitlab.com/core-27/c27cache"
keywords = ["fastapi", "caching", "cache", "simple"]


[tool.poetry.dependencies]
python = "^3.8"
pytz = "^2021.3"
python-dateutil = "^2.8.2"
pytest-asyncio = "0.15.1"
redis = "3.5.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pydantic = "^1.9.0"
fastapi = "^0.71.0"
ipython = "^8.0.0"
requests = "^2.27.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
