#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['ipwhl']

package_data = \
{'': ['*']}

entry_points = \
{'console_scripts': ['ipwhl-declck = ipwhl.declck:main',
                     'ipwhl-declgen = ipwhl.declgen:main',
                     'ipwhl-depsck = ipwhl.depsck:main',
                     'ipwhl-nameck = ipwhl.nameck:main',
                     'ipwhl-prefix = ipwhl.prefix:main',
                     'ipwhl-publish = ipwhl.publish:main']}

setup(name='ipwhl',
      version='1.0.0',
      description='Utilities for the InterPlanetary Wheels',
      author=None,
      author_email='Nguyễn Gia Phong <mcsinyx@disroot.org>',
      url=None,
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
