
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-20T16:05:01-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a786b4298cd2bcf819ad5a5f170f5f56b11baf78",
 "version": "2.2.14.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
