
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-20T22:32:16-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e538c4fb5c9873525bb87355f36e3ff87ac0ef53",
 "version": "1.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
